### ISSUE TITLE
Slurm MPI scaleset size defaults to 40

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#1016]
## In what area(s)?

/area job-scheduling

## Describe the feature

When using ColocateNodes, cyclecloud defaults to a scaleset size of 40. Azure can go up to 100. It would be nice if `Azure.MaxScalesetSize` was added to azhop-slurm.txt.j2, or if it was a user configurable parameter from config.yml

**Comment by xpillons** [comment]
I thought that the default value for Cycle has been increased from 40 to 100. Let me check.

**Comment by matt-chan** [comment]
I'm not sure. We were getting multiple partitions, each at 40 nodes without specifying that option in azhop-slurm.

**Comment by xpillons** [comment]
this is fine as long as you don't need a single MPI job to use more than 40 nodes. Would it be the case for your workloads ?

**Comment by ltalirz** [comment]
> this is fine as long as you don't need a single MPI job to use more than 40 nodes. Would it be the case for your workloads ?

Quite rare, but can happen.

**Comment by xpillons** [comment]
It is now possible to specify the maxscaleset value per node array in the config file since release 1.0.28
