### ISSUE TITLE
AD failures on worker creation

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#1022]
## In what area(s)?

 /area job-scheduling

## Expected Behavior

Nodes should start without any error messages.

## Actual Behavior

Cyclecloud reports AD failures when joining the domain. The cyclecloud website reports an error during cluster-init.

After about 5 minutes, some nodes start becoming "ready", and another 5 minutes later, the rest of the nodes are "ready". This error doesn't seem to be fatal

```
Script output:
 sssd-1.16.5-10.el7_9.13.x86_64
realmd-0.16.1-12.el7_9.1.x86_64
oddjob-0.31.5-4.el7.x86_64
oddjob-mkhomedir-0.31.5-4.el7.x86_64
adcli-0.8.1-16.el7_9.1.x86_64
samba-common-4.10.16-19.el7_9.noarch
samba-common-tools-4.10.16-19.el7_9.x86_64
krb5-workstation-1.15.1-54.el7_9.x86_64
openldap-clients-2.4.44-25.el7_9.x86_64
policycoreutils-python-2.5-34.el7.x86_64
Update nameserver
root: Domain join on hpc.azure
Password for hpcadmin: See: journalctl REALMD_OPERATION=r179.11315
realm: Couldn't join realm: Insufficient permissions to join the domain hpc.azure

root: Failed to domain join the server -  Attempt 1/3:
root: Domain join on hpc.azure
Password for hpcadmin: See: journalctl REALMD_OPERATION=r197.11335
realm: Couldn't join realm: Joining the domain hpc.azure failed

root: Failed to domain join the server -  Attempt 2/3:
root: Domain join on hpc.azure
Password for hpcadmin: See: journalctl REALMD_OPERATION=r214.11351
realm: Couldn't join realm: Insufficient permissions to join the domain hpc.azure

root: Failed to domain join the server -  Attempt 3/3:
root: Domain join on hpc.azure
Password for hpcadmin: See: journalctl REALMD_OPERATION=r231.11362
realm: Couldn't join realm: Joining the domain hpc.azure failed

root: Failed to domain join the server after 4 attempts.
```

## Steps to Reproduce the Problem

Create 10 colocated nodes for an MPI job at the same time. We used hc44 spot instances.

**Comment by xpillons** [comment]
ok, so this is the built in mechanism for retrying on transient errors. so if all nodes becomes ready and the job can start then it's the expected behavior. There could be many reason why joining a domain can failed, and with both retry logics in the script and by cycle you should be good.
