### ISSUE TITLE
sbatch does not support `--container-image` option

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1023]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation
> /area image
/area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Expected Behavior

`sbatch` installed on the ondemand VM recognizes the `--container-image` option, when `enroot_enabled` is set to `true` in the `config.yml`.

## Actual Behavior

While `srun` recognizes the option provided by the pyxis plugin
```
$ srun --help | grep -i container-image
      --container-image=[USER@][REGISTRY#]IMAGE[:TAG]|PATH
```

The following batch script fails:

```
$ cat test.sh
#!/bin/bash
#SBATCH --partition=hc44-low
#SBATCH --container-image=/path/to/image
pwd
```
```
$ sbatch test.sh
sbatch: unrecognized option '--container-image=/path/to/image'
Try "sbatch --help" for more information
```

However, [sbatch should support this option as well](https://github.com/NVIDIA/pyxis#sbatch) (basically a requirement for any non-interactive container job).

## Steps to Reproduce the Problem

See above

cc @matt-chan

**Comment by ltalirz** [comment]
Until this is fixed, a workaround is to call `srun` again from the batch script

`test.sh`
```bash
#!/bin/bash
#SBATCH --partition=hc44-low
srun --container-image=/path/to/image pwd
```
and then
`sbatch test.sh`

**Comment by xpillons** [comment]
@vgamayunov any idea why this ?

**Comment by vgamayunov** [comment]
there is a problem in this version of pyxis - will update to the newer version
