### ISSUE TITLE
ondemand writes to /mnt/resource, even though it's not mounted

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#1026]
## In what area(s)?

> /area ood

## Expected Behavior

Files should not be written to /mnt/resource unless it's mounted

## Actual Behavior

Ondemand has a few files written to /mnt/resource when it's not mounted.

```
# mountpoint /mnt/resource/
/mnt/resource/ is not a mountpoint

# ls /mnt/resource/
ondemand-nginx  passenger-tmp
```

## Steps to Reproduce the Problem

Default install

**Comment by ltalirz** [comment]
There is also the `#FIXME` in the cluster-init script that mentions /mnt/resource is not available in Ubuntu.
https://github.com/Azure/az-hop/blob/8898d87e0d4b1bea09d1e2ffed0bb8f02e49d5ee/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/5-default.sh.j2#L10-L11

It might make sense to generalize this concept of the ephemeral disk a bit, including the check for its presence/absence.

**Comment by xpillons** [comment]
When does the files are written to /mnt/resource ? This mount it a default one on Azure VMs with CentOS so it should be mounted after the machine is booted.

**Comment by ltalirz** [comment]
Hi Xavier, this issue is about the `ondemand` VM writing to `/mnt/resource` (although on the `ondemand` VM this is not the mount point of an epheremal disk).
See above for which folders are created there, I did not look specifically into who was writing them (nginx, passenger)

**Comment by xpillons** [comment]
so I don't get it because /mnt/resource exists on the ondemand VM which is mounted on the local SSD temporary disk.

**Comment by xpillons** [comment]
Isn't it fine as long as the /mnt/resource exists ? performances will be impacted if running on a standard disk rather than SSD.

**Comment by ltalirz** [comment]
It is possible that this is not a problem.
It just indicated to us that some applications may assume the presence of a fast ephemeral disk, when it does not actually exist. Feel free to close from my side

**Comment by xpillons** [comment]
this should be fine for ondemand, and I agree can be an issue for compute nodes. on Compute Nodes, if there is NVMe detected at boot time, then these are mounted in RAID0 and exposed thru the /mnt/nvme mount point.
