### ISSUE TITLE
location specified in `config.yml` not respected when using existing resource group

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1030]
## In what area(s)?

/area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Expected Behavior

When specifying a `location` in the `config.yml`, az-hop is deployed in this location (independent of the location of the resource group used).

## Actual Behavior

When using a pre-existing resource group, the location of that resource group takes precedence over the location specified by the user.

## Steps to Reproduce the Problem

Create a resource group, e.g. in westus.
Tell az-hop to use that resource group for deployment, but ask to deploy in eastus.

It is quite straightforward to fix once accepted as a bug - I don't know whether there would be a reason to stick with the current behavior where the location of the resource group takes precedence.

cc @matt-chan

**Comment by ltalirz** [comment]
In the scenario mentioned above, one hits another issue when building images:
when giving the packer azure/arm plugin a destination resource group, it will create the VM in the region of that resource group (no way to change this, see [issue](https://github.com/hashicorp/packer-plugin-azure/issues/224)).

Our workaround was to create a separate vnet in the resource group, build the image there, and then replicate it to the target region.

**Comment by xpillons** [comment]
it's a best practice to deploy resources in the same location of the resource group, and usually RG are also named with the location code.

**Comment by ltalirz** [comment]
If the scenario is not going to be supported, it would be good to document the requirement that the location of the pre-existing resource group must match the location in the `config.yml`.

**Comment by xpillons** [comment]
closed by https://github.com/Azure/az-hop/commit/aa0e5d7b1e23a4666352e9cd797706e12257c9f3
