### ISSUE TITLE
terraform azurerm provider version update

### ISSUE THREAD

**Issue by scstevenson** [Azure/az-hop#1033]
terraform refresh fails with below error in AzureUSGovernment.
`│ Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context canceled
│
│   with azurerm_key_vault.azhop,
│   on keyvault.tf line 6, in resource "azurerm_key_vault" "azhop":
│    6: resource "azurerm_key_vault" "azhop" {
│
╵
`
Updating tf/main.tf to specify current version of azurerm provider allows terraform refresh to succeed.
`terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.17.0"
    }
`

**Comment by xpillons** [comment]
we will update the provider version in the next release, but can't backport it to previous ones.
