### ISSUE TITLE
support specific naming convention

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1034]
## In what area(s)?

/area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Describe the feature
Some customers follow specific naming conventions for Azure resources, for example instead of `scheduler` they would prefer something like `myhop-vm-scheduler-eus-dev` (i.e., here, adding a prefix and suffix based on resource type, region and development status).

While the name of the vnet, the subnets and the application security groups can be controlled from the `config.yml`, it seems like the names of the vms are hardcoded (or at least it is not clear from the template configuration how to change them).

There is obviously also a tradeoff with complexity here, which need to be considered.
In any case, I am recording the customer request here.

**Comment by xpillons** [comment]
Yes this looks a good request, we need to assess the impact as we are also working on a bicep deployment version.

**Comment by ltalirz** [comment]
There is also this set of recommendations https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming which we've been pointed to.

Of the possible components mentioned there, it may be useful to at least include a prefix with the resource type, e.g. `vm-ondemand` instead of `ondemand`, etc. This is already the case for the application security groups (`asg-`) but it is not applied consistently throughout all az-hop resources.

Overall, it would be great to write down a naming rule for resources deployed by AZ-HOP (even if aspirational and to be implemented later).`

**Comment by xpillons** [comment]
There will be some constraints on the naming rules because of the domain join of the machine limiting name lenght.

**Comment by xpillons** [comment]
VM can now be renamed in the configuration file
