### ISSUE TITLE
set storage account to not be publicly accessible

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1035]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Describe the feature

Customer policy may require storage accounts to not be publicly accessible.

Unfortunately, the azurerm terraform provider currently does not support setting this property at creation time.
Fix once https://github.com/hashicorp/terraform-provider-azurerm/issues/16335 is addressed

cc @matt-chan

**Comment by ltalirz** [comment]
Note: currently, access to the Azure storage account is handled via specific network security rules.
When setting `publicNetworkAccess = 'disabled'`, all access is blocked an these rules are no longer  in effect.

The only solution for this scenario is to [create a private endpoint](https://docs.microsoft.com/en-us/azure/storage/common/storage-private-endpoints) for the storage account.

**Comment by xpillons** [comment]
Private endpoints will be the way to go in the future. Right now storage account access is only possible from the admin and compute subnets when working in a network lockdown scenario (no public ip). This rule is controlled by the network rules on the storage account, which is like a firewall.

**Comment by ltalirz** [comment]
Just mentioning that setting the `PublicNetworkAccess` property on the storage account should now be possible via terraform (v3.21.0 of the azurerm terraform provider).

https://github.com/hashicorp/terraform-provider-azurerm/issues/16335#issuecomment-1251465055

**Comment by ltalirz** [comment]
It looks like we will need to implement the private endpoint solution for the storage account for a customer until end of November.

@xpillons I don't know whether you have the time to look into this on your side, but if you have any specific hints / examples that you can share that could already be very helpful

**Comment by xpillons** [comment]
close as duplicated with #1219
