### ISSUE TITLE
optional support for purge protection on key vault

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1037]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling

/area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Describe the feature
Customer policy may require purge protection to be enabled on the key vault (`purge_protection_enabled = true`).
https://github.com/Azure/az-hop/blob/8898d87e0d4b1bea09d1e2ffed0bb8f02e49d5ee/tf/keyvault.tf#L6

Perhaps this could be an option in the `config.yaml`?

A more general question would be: since I'm sure the security policies of customers vary quite a bit, would there be a way in terraform to "inquire" about whether a certain feature (like the one above) is mandated by a policy, and decide what to do based on the outcome of that inquiry?

**Comment by xpillons** [comment]
if this is a blocker on the customer side, then we can consider adding an option. 
for your suggestion, that would be complex to implement, with higher privilege needed and probably too customer specific.

**Comment by ltalirz** [comment]
Let's close this for the moment. Will reopen in case we encounter this requirement again.
