### ISSUE TITLE
Guide Issues : Running Packer with Newer Type VM's causes issues.

### ISSUE THREAD

**Issue by yoyomonkey1** [Azure/az-hop#1044]
Going through the tutorial using 1.0.25 and South Central US.

VM used for 3d Desktop :  Standard_NV12s_v3

When on Lab 1 Task 3: Build Images  the NV6 not many regions had this available for my subscription so kept it as NV12s_v3 . Everything seems to work till the end and it came with the following error. 

`Creating an image definition for azhop-centos79-desktop3d
Read image definition from ../config.yml
/subscriptions/3f0748f2-5c3e-4edf-acea-7749f0ad2517/resourceGroups/azhop-lab1/providers/Microsoft.Compute/galleries/azhop_gve0h3q8/image
s/azhop-centos79-desktop3d
Looking for image azhop-centos79-desktop3d version  ...
Pushing version 7.8.220822203 of azhop-centos79-desktop3d in azhop_gve0h3q8
(Conflict) The resource with id '/subscriptions/3f0748f2-5c3e-4edf-acea-7749f0ad2517/resourceGroups/azhop-lab1/providers/Microsoft.Compu
te/images/azhop-centos79-desktop3d' has a different Hypervisor generation ['V2'] than the parent gallery image Hypervisor generation ['V
1'].
Code: Conflict
Message: The resource with id '/subscriptions/3f0748f2-5c3e-4edf-acea-7749f0ad2517/resourceGroups/azhop-lab1/providers/Microsoft.Compute
/images/azhop-centos79-desktop3d' has a different Hypervisor generation ['V2'] than the parent gallery image Hypervisor generation ['V1'
].`

**Comment by xpillons** [comment]
Please make sure that the hypervisor version of the image is set to v2 in the configuration file if you use NV12s_v3.
Before rebuilding the image, delete the image definition in the gallery as it has been created with v1.

**Comment by yoyomonkey1** [comment]
Apologies need some help. How do i set hte version to v2 .  
Both json files have 
Have the same "image sku": "7_9-gen2" 


Here is the  builders azhop-centos79-v2-rdma-gpgpu.json
' "builders": [
        {
            "type": "azure-arm",
            "use_azure_cli_auth": "{{user `var_use_azure_cli_auth`}}",
            "image_publisher": "OpenLogic",
            "image_offer": "CentOS-HPC",
            "image_sku": "7_9-gen2",
            "image_version": "latest",
            "managed_image_resource_group_name": "{{user `var_resource_group`}}",
            "managed_image_name": "{{user `var_image`}}",
            "os_type": "Linux",
            "vm_size": "Standard_NV12s_v3",
            "managed_image_storage_account_type": "Premium_LRS",
            "ssh_pty": "true",
            "build_resource_group_name": "{{user `var_resource_group`}}",
            "private_virtual_network_with_public_ip": "{{user `var_private_virtual_network_with_public_ip`}}",
            "virtual_network_name": "{{user `var_virtual_network_name`}}",
            "virtual_network_subnet_name": "{{user `var_virtual_network_subnet_name`}}",
            "virtual_network_resource_group_name": "{{user `var_virtual_network_resource_group_name`}}",
            "cloud_environment_name": "{{user `var_cloud_env`}}",
            "ssh_bastion_host": "{{user `var_ssh_bastion_host`}}",
            "ssh_bastion_port": "{{user `var_ssh_bastion_port`}}",
            "ssh_bastion_username": "{{user `var_ssh_bastion_username`}}",
            "ssh_bastion_private_key_file": "{{user `var_ssh_bastion_private_key_file`}}"
        }
    ],'

And the rdma json file which is listing as v2 in the compute gallery : 


{
    "builders": [
        {
            "type": "azure-arm",
            "use_azure_cli_auth": "{{user `var_use_azure_cli_auth`}}",
            "image_publisher": "OpenLogic",
            "image_offer": "CentOS-HPC",
            "image_sku": "7_9-gen2",
            "image_version": "latest",
            "managed_image_resource_group_name": "{{user `var_resource_group`}}",
            "managed_image_name": "{{user `var_image`}}",
            "os_type": "Linux",
            "vm_size": "Standard_d8s_v3",
            "managed_image_storage_account_type": "Premium_LRS",
            "ssh_pty": "true",
            "build_resource_group_name": "{{user `var_resource_group`}}",
            "private_virtual_network_with_public_ip": "{{user `var_private_virtual_network_with_public_ip`}}",
            "virtual_network_name": "{{user `var_virtual_network_name`}}",
            "virtual_network_subnet_name": "{{user `var_virtual_network_subnet_name`}}",
            "virtual_network_resource_group_name": "{{user `var_virtual_network_resource_group_name`}}",
            "cloud_environment_name": "{{user `var_cloud_env`}}",
            "ssh_bastion_host": "{{user `var_ssh_bastion_host`}}",
            "ssh_bastion_port": "{{user `var_ssh_bastion_port`}}",
            "ssh_bastion_username": "{{user `var_ssh_bastion_username`}}",
            "ssh_bastion_private_key_file": "{{user `var_ssh_bastion_private_key_file`}}"
        }
    ],

Thanks in advance . Been trying to run the tutorial mulitple time to get a consistent working build . 
Due to specific vm's not being availalble to my subscription due to region limitations etc. I am looking to document a consistent approach with additional steps  use the similar newer generation vm available in a region .

**Comment by xpillons** [comment]
ok, the change has to be done in the config.yml in the queue section. This one defines the custom image definitions that needs to be preset in the image gallery.
Change the hyper_v value to V2 for your desktop3D definition.

**Comment by xpillons** [comment]
@yoyomonkey1 have you solved your issue ?

**Comment by yoyomonkey1** [comment]
in the config.yml file i changed the following

'- name: azhop-centos79-desktop3d
publisher: azhop
offer: CentOS
sku: 7_8
hyper_v: V1 # I changed this to V2 
os_type: Linux
version: 7.8

And this worked. 

the further steps worked until Excercise 3 : Task 2

tried to connect to the On-Demand Platform and the site refused to connect.   Tried running the install.sh multiple times and there was no error but still cannot connect .

**Comment by xpillons** [comment]
ok, this is weird. Which kind of connection error do you get ? building an image and connecting to the portal are two different things with no relations.

**Comment by yoyomonkey1** [comment]
I deleted everything and done it all from scratch ...with the VM at NV12s_V3 instead of the NV6  to the changes in the Hyper V version in the config.yml . Every command worked with no errors.  

When it came to connecting to the ondemand pc so that I can log in : 
The error that comes back is : 
ondemand1XXXXX.southcentralus.cloudapp.azure.com refused to connect.

I have switched it off and on again and still the same error. 

Tried in different browsers from Chrome, Edge and Brave .

**Comment by xpillons** [comment]
can you resolve this DNS name ?

**Comment by yoyomonkey1** [comment]
yes dns resolves to an ip and I have tried both ip and dns same issue

**Comment by xpillons** [comment]
and you use https://ondemand1XXXXX.southcentralus.cloudapp.azure.com ?
can you send a screenshot of the error ?

**Comment by yoyomonkey1** [comment]
No not yet. currently tying up some loose ends and will be dedicating
myself to AZ-HOP for the next week .

Cheers

Jazz
