### ISSUE TITLE
configure_aad.sh reports insufficient permissions

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#1065]
## In what area(s)?

 /area user-management

## Expected Behavior

configure_aad.sh should have permissions to make changes

## Actual Behavior

It reports insufficient permissions. The offending line in the script is:

```
++ az ad app list --display-name poboy --query '[].id' -o tsv
ERROR: Insufficient privileges to complete the operation. 
```

The system managed principle has Contributor, Reader, and User Access Administrator on the subscription (which is already more than what the documentation requests)

## Steps to Reproduce the Problem

Create new deployment with OIDC. Run configure_aad.sh

**Comment by xpillons** [comment]
Usually this is done by a subscription admin. So to create an application to be registered as OIDC this needs to be done by a subscription owner.

**Comment by xpillons** [comment]
Closed by https://github.com/Azure/az-hop/commit/e05e40a3860a4facc150f42b6271ad20bcd2107b
