### ISSUE TITLE
code server app: unable to select project directory

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1073]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
/area ood
> /area remote-visualization
> /area user-management

## Expected Behavior

Can launch Code server app from OOD portal and select project directory

## Actual Behavior

When clicking on "select project directory", I see
<img width="253" alt="image" src="https://user-images.githubusercontent.com/1053245/188149503-1fcba56e-560d-431a-ba73-0ee17f7e8667.png">

This is from the Javascript console
<img width="547" alt="image" src="https://user-images.githubusercontent.com/1053245/188149774-be7c924a-620d-41a9-9191-926d23f8305d.png">

## Steps to Reproduce the Problem
 - log in to OOD portal
 - click on Code server app
 - click on "select project directory"

**Comment by xpillons** [comment]
I can repro as well. Look like the url is wrong
