### ISSUE TITLE
sssd crashes on ondemand portal

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1074]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring

/area ood
> /area remote-visualization
> /area user-management

## Expected Behavior

sssd does not crash

## Actual Behavior

We noticed that the sssd service on the `ondemand` VM crashed (killed by its own [watchdog service](https://sssd.io/contrib/debugging-sssd.html#disabling-the-watchdog), likely for exceeding some timeout). Afterwards, it was not able to restart automatically: 
```
[8155]: Child [8156] ('hpc.azure':'%BE_hpc.azure') was terminated by own WATCHDOG. Consult corresponding logs to figure out the
Sep 02 13:44:15 ondemand sssd[sssd][8155]: Child [8157] ('nss':'nss') was terminated by own WATCHDOG. Consult corresponding logs to figure out the reason.
Sep 02 13:45:05 ondemand sssd[be[hpc.azure]][30171]: Starting up
Sep 02 13:45:05 ondemand sssd[nss][30184]: Starting up
Sep 02 13:45:05 ondemand sssd[nss][30245]: Starting up
Sep 02 13:45:07 ondemand sssd[nss][30248]: Starting up
Sep 02 13:45:11 ondemand sssd[nss][30254]: Starting up
Sep 02 13:45:11 ondemand sssd[sssd][8155]: Exiting the SSSD. Could not restart critical service [nss].
Sep 02 13:45:37 ondemand sssd[pam][8158]: Shutting down
Sep 02 13:45:38 ondemand systemd[1]: sssd.service: main process exited, code=exited, status=1/FAILURE
Sep 02 13:45:38 ondemand systemd[1]: Unit sssd.service entered failed state.
```
Since this service is required for AD, after that it was no longer possible to log into `ondemand` via SSH as an AD user.

Restarting the sssd service manually solved the issue.

Upon inspecting the sssd logs, we noticed excessive amounts of the following logs right before the crash
```
Sep 02 16:53:16 ondemand sssd[be[hpc.azure]][7725]: Warning: user would have been denied GPO-based logon access if the ad_gpo_access_control option were set to enforcing mode.
```
After further inspection, we found that 8 such log messages were generated for every page visit on the ondemand web portal.

Our working theory is that these large number of requests eventually overloaded the AD server and led to the timeout (although we don't know exactly what is going on).

## Steps to Reproduce the Problem

Not sure whether this will be the case in every deployment, but for us:

* Connect to `ondemand` as `hpcadmin` and monitor `sudo journalctl  -u sssd.service  -f`
* Now log in to the `ondemand` web portal and click around
* For every click, 8 log messages are generated in the log above

cc @matt-chan

**Comment by xpillons** [comment]
Reading this article https://access.redhat.com/solutions/4685441 it can you try to apply the workaround and see if it works ? if so we will add this by default.

**Comment by xpillons** [comment]
I've this too on my cluster and it's not crashing sshd

**Comment by xpillons** [comment]
It had happened on 1.0.33 on one of our internal environment

**Comment by xpillons** [comment]
Workaround is to restart on failure /usr/lib/systemd/system/sssd.service

```
Restart=on-failure
RestartSec=30s
```

**Comment by ltalirz** [comment]
That would already be a helpful addition
