### ISSUE TITLE
add ubuntu 20.04 image

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1165]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation

/area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Describe the feature
I noticed the new AzHOP Compute images on the azure marketplace, very nice!

We have some questions/comments in this regard:

 1. Would it be possible to support ubuntu 20.04 as well? We are using ubuntu 20.04 for our workstations, so this would allow us to have the same image on the cluster
 2. The CentOS 7.9 HPC image has some known deficiencies that [are not going to be fixed because the azhpc developers consider it EOL](https://github.com/Azure/azhpc-images/pull/102). Given that [AlmaLinux 8.6 is now available from azhpc images](https://github.com/Azure/azhpc-images) perhaps it makes sense to offer that instead?
 3. I notice that while the CentOS image is shown as "free", the ubuntu image is shown as "bring your own license". Is that intentional?

<img width="250" alt="image" src="https://user-images.githubusercontent.com/1053245/198355390-02423d89-8a48-4b49-bf3d-2a2b91c87c7f.png">

Cheers!
Leo

cc @matt-chan

**Comment by xpillons** [comment]
1. Is this for compute or remote desktop ? compute would be easier to start as there are less dependencies than desktop
2. we are planning to have alma linux too, don't know which version to support, still in discussion
3. yes as free was not an option.

**Comment by ltalirz** [comment]
Thanks for the quick reply @xpillons 

 1. Here we're asking for support on the compute side
 2. I see, we'd be interested in the outcome of this discussion!
 3. May I ask where this restriction came from? Canonical [explicitly states in its Azure offerings that no license is required](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/canonical.0001-com-ubuntu-minimal-focal?tab=Overview)

**Comment by xpillons** [comment]
1. OK
2. OK
3. comes from the partner portal when creating the offer, will try to change it to free if possible.

**Comment by ltalirz** [comment]
> 3\. comes from the partner portal when creating the offer, will try to change it to free if possible.

Cheers! I just mentioned it since if I did not already know that ubuntu does not require a license, reading "BYOL" in the offering would stop me from using it.

**Comment by xpillons** [comment]
Image is now available in the marketplace under this URN azhpc:azhop-compute:ubuntu-20_04:latest
