### ISSUE TITLE
Long queue names cause AD realm join failures.

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#1191]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Expected Behavior

Long queue names should not affect node behavior, or long queue names should be rejected.

## Actual Behavior

If queue names are long (e.g. hc44-low-mpi), the node hostname can be too long for AD and it gets truncated. This causes a realm join failure. MPI nodes make it worse because they add more characters to the hostname for the placement group. 

This is documented here: https://techcommunity.microsoft.com/t5/windows-server-for-it-pro/hostname-character-limit/m-p/1068231

## Steps to Reproduce the Problem

Create a queue with a long name. 

This bug shows up in journalctl on the failing node:
```
Nov 08 17:47:16 hc44-low-mpi-pg0-2 root[13879]: Domain join on hpc.azure
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]: client using service: :1.77
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]: holding daemon: :1.77
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]: Using 'r651.13881' operation for method 'Discover' invocation on 'org.freedesktop.realmd.Provider' interface
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]: Registered cancellable for operation 'r651.13881'
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]:  * Resolving: _ldap._tcp.hpc.azure
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]:  * Resolving: _ldap._tcp.hpc.azure
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]:  * Performing LDAP DSE lookup on: 10.2.3.4
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]:  * Performing LDAP DSE lookup on: 10.2.3.4
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]: Searching  for (objectClass=*)
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]: Got defaultNamingContext: DC=hpc,DC=azure
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]: Sending TCP Netlogon request
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]: Received TCP Netlogon response
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]:  * Successfully discovered: hpc.azure
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]:  * Successfully discovered: hpc.azure
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]: Using 'r651.13881' operation for method 'Join' invocation on 'org.freedesktop.realmd.KerberosMembership' interface
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]: Registered cancellable for operation 'r651.13881'
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]: holding daemon: current-invocation
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]:  * Required files: /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd, /usr/bin/net
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]:  * Required files: /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd, /usr/bin/net

Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]:  * Joining using a truncated netbios name: HC44-LOW-MPI-PG
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]:  * Joining using a truncated netbios name: HC44-LOW-MPI-PG

Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]:  * LANG=C LOGNAME=root /usr/bin/net -s /var/cache/realmd/realmd-smb-conf.2X52U1 -U hpcadmin ads join hpc.azure
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]:  * LANG=C LOGNAME=root /usr/bin/net -s /var/cache/realmd/realmd-smb-conf.2X52U1 -U hpcadmin ads join hpc.azure
Nov 08 17:47:16 hc44-low-mpi-pg0-2 realmd[13501]: process started: 13886
Nov 08 17:47:20 hc44-low-mpi-pg0-2 realmd[13501]: Enter hpcadmin's password:connect_to_domain_password_server: unable to open the domain client session to machine ad.hpc.azure. Flags[0x00000000] Error was : NT_STATUS_NO_TRUST_SAM_ACCOUNT.
Nov 08 17:47:20 hc44-low-mpi-pg0-2 realmd[13501]: Enter hpcadmin's password:connect_to_domain_password_server: unable to open the domain client session to machine ad.hpc.azure. Flags[0x00000000] Error was : NT_STATUS_NO_TRUST_SAM_ACCOUNT.
Nov 08 17:47:20 hc44-low-mpi-pg0-2 realmd[13501]:
Nov 08 17:47:20 hc44-low-mpi-pg0-2 realmd[13501]:
Nov 08 17:47:20 hc44-low-mpi-pg0-2 realmd[13501]: Failed to join domain: failed to verify domain membership after joining: The SAM database on the Windows Server does not have a computer account for this workstation trust relationship.
Nov 08 17:47:20 hc44-low-mpi-pg0-2 realmd[13501]: Failed to join domain: failed to verify domain membership after joining: The SAM database on the Windows Server does not have a computer account for this workstation trust relationship.
Nov 08 17:47:20 hc44-low-mpi-pg0-2 realmd[13501]: process exited: 13886
Nov 08 17:47:20 hc44-low-mpi-pg0-2 realmd[13501]:  ! Joining the domain hpc.azure failed
Nov 08 17:47:20 hc44-low-mpi-pg0-2 realmd[13501]:  ! Joining the domain hpc.azure failed
Nov 08 17:47:20 hc44-low-mpi-pg0-2 realmd[13501]: released daemon: current-invocation
Nov 08 17:47:20 hc44-low-mpi-pg0-2 realmd[13501]: client gone away: :1.77
Nov 08 17:47:20 hc44-low-mpi-pg0-2 realmd[13501]: released daemon: :1.77
```

cc: @ltalirz

**Comment by xpillons** [comment]
Thanks @matt-chan , look like Netbios is used under the cover. So queue names should be limited to 9 or 10 characters.

**Comment by ltalirz** [comment]
https://github.com/Azure/az-hop/pull/1353 now enforces a maximum length of 9 characters.

Note that this allows for suffixes of the form `-pg1-1` (6 extra characters).
In queues with large numbers of cores (e.g. up to 100 placement groups with 100 VMs each), however, the maximum addition to the queue name is `-pg100-100`, i.e. another 10 characters.

This would limit queue length to 5 characters, which basically forces queue names to be non-intuitive  abbreviations.

The only real solution here is to move to a technology that can support node names beyond 15 characters (or define a mapping from a given queue name to a shorter node name prefix, if that is possible).

**Comment by xpillons** [comment]
15 characters is enforce by NETBIOS and AD, so in order to find a way to extend this we have to understand if netbios can be avoided. 
The limit should be 10 today as `largeviz3d` requires it. 
In addition, limiting scaleset to 99 will save a character in the naming for large scale deployments. the -pgXXX is added by CC and I don't know exactly if the -pgXXX is really used or if it's only cosmetic. We need to ask the CC team.

**Comment by ltalirz** [comment]
> The limit should be 10 today as largeviz3d requires it.

The schema currently has an exception for 'special' queues like `largeviz3d` (which makes sense as some of these may not require placement groups and thus require less stringent character limits)


> the -pgXXX is added by CC and I don't know exactly if the -pgXXX is really used or if it's only cosmetic. We need to ask the CC team.

I see. As long as new jobs will still be placed on VMs within a placement group by default, I think exposing this placement group in the hostnames is usually more confusing to users than helpful.
It is very rare that someone needs to manually pin a new job to a specific subset of nodes within a placement group that has already been allocated.

Can you ask them please?

**Comment by xpillons** [comment]
queue name is now limited by the schema
