### ISSUE TITLE
Metric alerts

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#1192]
## In what area(s)?

 /area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Describe the feature

Hi Xavier,

It would be nice if we could get alerted when disks are nearly running out of space. Today our ANF was nearly full and we've had times in the past where the OS disk was full on various VMs. 

Would it be possible to set up azure monitoring to notify us by email or something when it is full? Another option might even be to automatically increase the ANF size (but this might be abused). I think this would make our deployments more reliable for customers.

cc @ltalirz

**Comment by matt-chan** [comment]
Ah I just saw #1183 .... I'll let you close this one if you think grafana is a better solution!

**Comment by xpillons** [comment]
Yes, look at this as others had the same issue. I don't know if azure monitoring will be able to handle this as it's not the disk out of space but rather the volume created on the disk. 
I won't automatically increase ANF size as this will have an impact on cost, and usually customers wants to stay in control of their ANF volumes.

**Comment by xpillons** [comment]
closed by #1265
