### ISSUE TITLE
pyxis upgrade to support passing environment variables

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1245]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Describe the feature
This is just a placeholder to please upgrade pyxis when the next pyxis version is released.

The latest commit https://github.com/NVIDIA/pyxis/commit/5164d82a6b8099c294fb512437afd85542578df6 adds a very useful `--container-env` parameter, which allows a more straightforward passing of environment variables into the application container.

**Comment by ltalirz** [comment]
New pyxis release is out https://github.com/NVIDIA/pyxis/releases/tag/v0.15.0

Besides the new `--container-env` flag, there are other important improvements over v0.12 that is currently used in az-hop (e.g. it no longer exports locales from the user environment, which may not be available in the container).

This upgrade will be quite useful for us

**Comment by xpillons** [comment]
@vgamayunov can you please have a look ?

**Comment by vgamayunov** [comment]
on it

**Comment by ltalirz** [comment]
Fantastic, thanks a lot Victor!

**Comment by ltalirz** [comment]
cc @matt-chan 

this would also have addressed the locale issue we ran into
