### ISSUE TITLE
Unable to finish network setup for new volume (IP range clash)

### ISSUE THREAD

**Issue by ankurkapil2020** [Azure/az-hop#1275]
Hi 
I am trying to install the Azure HPC OnDemand Platform using the tutorial.
https://azure.github.io/az-hop/
https://azure.github.io/az-hop/tutorials/quickstart.html#task-1-connect-to-a-cloud-shell-session

However, I am having the errors 
Unable to finish network setup for new volume (IP range clash)

Please find the detailed message.
Thanks!

Kind regards

ERROR: {'status':'Failed','error':{'code':'DeploymentFailed','message':'At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.','details':[{'code':'Conflict','message':'{\\r\\n  \\'status\\': \\'Failed\\',\\r\\n  \\'error\\': {\\r\\n    \\'code\\': \\'ResourceDeploymentFailure\\',\\r\\n    \\'message\\': \\'The resource operation completed with terminal provisioning state 'Failed'.\\',\\r\\n    \\'details\\': [\\r\\n      {\\r\\n        \\'code\\': \\'InternalServerError\\',\\r\\n        \\'message\\': \\'Unable to finish network setup for new volume (IP range clash). Please try again, if this problem persists please contact support for assistance and provide the CorrelationId 'fc5332d5-16ac-430f-9bba-41e03f6a15f1'\\',\\r\\n        \\'details\\': [\\r\\n          {\\r\\n            \\'code\\': \\'InternalServerError\\',\\r\\n            \\'message\\': \\'Unable to finish network setup for new volume (IP range clash). Please try again, if this problem persists please contact support for assistance and provide the CorrelationId 'fc5332d5-16ac-430f-9bba-41e03f6a15f1'\\'\\r\\n          }\\r\\n        ]\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}'},{'code':'Conflict','message':'{\\r\\n  \\'error\\': {\\r\\n    \\'code\\': \\'ConflictError\\',\\r\\n    \\'message\\': \\'A vault with the same name already exists in deleted state. You need to either recover or purge existing key vault. Follow this link https://go.microsoft.com/fwlink/?linkid=2149745 for more information on soft delete.\\'\\r\\n  }\\r\\n}'}]}}

**Comment by xpillons** [comment]
Hi Ankur. It look like you have already tried to deploy one in the same resource group as per the keyvault error message.
Please remove the whole resource group and try to deploy with a new resource group name.

**Comment by ankurkapil2020** [comment]
Hi 
I have deleted the resource group and purged the vault.
However, I am still getting the following error related to IP range for new volume.
Could you please help?

ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"InternalServerError\",\r\n        \"message\": \"Unable to finish network setup for new volume (IP range clash). Please try again, if this problem persists please contact support for assistance and provide the CorrelationId '53b8277e-ca30-490e-9815-f7f1dd6353a1'\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"InternalServerError\",\r\n            \"message\": \"Unable to finish network setup for new volume (IP range clash). Please try again, if this problem persists please contact support for assistance and provide the CorrelationId '53b8277e-ca30-490e-9815-f7f1dd6353a1'\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"RetryableError\",\r\n        \"message\": \"A retryable error occurred.\"\r\n      }\r\n    ]\r\n  }\r\n}"}]}

**Comment by xpillons** [comment]
I just did a test and it passed in our environment. There should be something special in your subscription that generate this error. Have you done any updates in the build.yml file before running the deploy.sh script ?
Could you please try to update the 10.201 cidr to something different like 10.100 ?

**Comment by ankurkapil2020** [comment]
hi. I have tried a couple of different IP but not much luck so far. Let me try to discuss this with my IT.

**Comment by xpillons** [comment]
@ankurkapil2020 it look like this was an internal ANF issue. Would you mind trying it again ? And in case of error, rerun the build.sh -a apply again ? Thx
