### ISSUE TITLE
Issue in Exercise 1 Task 6

### ISSUE THREAD

**Issue by tejaswini972** [Azure/az-hop#1297]
## Expected Behavior

[Exercise 1 Task 6](https://github.com/Azure/az-hop/blob/main/docs/tutorials/quickstart.md#task-6--monitor-the-installation-progress): As per the instructions, after deploying the resources **Cloud init script** execution should be successful.

## Actual Behavior

Even though resource deployment is successful, **Cloud init script** is failing with the below error.

```
2023-01-20 12:13:33,270 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2023-01-20 12:13:33,288 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/pytho
n3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 22.4.2-0ubuntu0~20.04.2 finished at Fri, 20 Jan 2023 12:13:33 +0000. Datasource DataSourceAzure [seed=/dev/sr0].  Up 1888.
46 seconds
```

Have attached the screenshot below for reference.

<img width="915" alt="2023-01-20_17-44-25" src="https://user-images.githubusercontent.com/52440474/213699082-fdc59aca-7a1e-427b-a40b-d1b6d1c5336e.png">

**Comment by xpillons** [comment]
There is actually a breaking change and version v1.0.29 should be used instead of main when doing the deployment in Task4. I've updated the doc. There are 2 ways for continuing here :
- restart from scratch, dropping the resource group and redeploying with a new resource group name
- or from the deployer VM
  - cd /az-hop
  - git checkout v1.0.29
  - ./install.sh

**Comment by kalyani7744** [comment]
Hello @xpillons, we have tried the workarounds provided above for the issue but there is no luck.

- When we restarted from scratch and redeployed the resource group, we are getting the same error as mentioned by @tejaswini972 with the following error message

  ![image](https://user-images.githubusercontent.com/83349665/214029240-39ae8250-bc52-4f9b-b5dd-653c65ab12e5.png)

- While trying to login to the deployer VM as root and running the commands, I am getting an error with **Primary DNS** while running `./install.sh` command. Please find the error details below:

   ![image](https://user-images.githubusercontent.com/83349665/214029635-24dc1bae-c700-429c-9f17-18adc4c0aadc.png)

 Could you please help us out here?

**Comment by xpillons** [comment]
@kalyani7744 I just realized that option 2 was not possible because of some variable name changed hence the primary_dns issue.

For the first option, please make sure to specify the release v1.0.29 in these two commands  :
- git clone https://github.com/Azure/az-hop.git -b v1.0.29
- ./deploy.sh azhop_quickstart <location> v1.0.29

**Comment by kalyani7744** [comment]
@xpillons , we have specified the release version with the above 2 commands and tried. We are still facing same issue with the below error:

```
2023-01-20 12:13:33,270 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2023-01-20 12:13:33,288 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/pytho
n3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 22.4.2-0ubuntu0~20.04.2 finished at Fri, 20 Jan 2023 12:13:33 +0000. Datasource DataSourceAzure [seed=/dev/sr0].  Up 1888.
46 seconds
```
  ![image](https://user-images.githubusercontent.com/83349665/214038028-c5b4f55f-fec4-4b35-86e1-96d344b6c037.png)

**Comment by xpillons** [comment]
Can you please provide the content of /az-hop/playbooks/group_vars/all.yml ?

**Comment by kalyani7744** [comment]
Please find the content of all.yml file below:

![image](https://user-images.githubusercontent.com/83349665/214041872-4f22e59e-8e22-4c6b-aa73-5c45cc18b0ac.png)

**Comment by xpillons** [comment]
Ok, so it look like the branch is not checkout, which means it's not provided as an input to the bicep deployment script or with a wrong value. 

On the deployer VM can you run "git status" under the /az-hop folder ?
You should have something like this :

```
root@deployer:/az-hop# git status
HEAD detached at v1.0.29
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
modified:   playbooks/roles/ood-ansible (new commits)

```
I guess there is a mistake in running this command 
![image](https://user-images.githubusercontent.com/7349410/214054433-ace11faf-3283-4e83-bc44-547559a82284.png)

Please check your inputs and try in a different resource group from scratch.
Thank you

**Comment by shashankms9** [comment]
Hey @xpillons, in [ex1-task6](https://github.com/Azure/az-hop/blob/main/docs/tutorials/quickstart.md#task-6--monitor-the-installation-progress) still facing these same issues, we can see that one of the certificate failed to download and Cloud-init script is failing with the below error: 

Find out the screenshots below:

![image](https://user-images.githubusercontent.com/104433795/217846946-f847f331-7ecf-41cf-afc2-6d9bc80107bc.png)

![image](https://user-images.githubusercontent.com/104433795/217846731-e43f0582-0ba9-4a78-8916-5ff66ec60404.png)

![image](https://user-images.githubusercontent.com/104433795/217846581-3ddeb149-2249-47b8-99c2-ce3a0d3fed3e.png)

**Comment by xpillons** [comment]
It look like the CVMFS repo is down. disable that option by doing this :
- connect on the deployer VM with root
- cd /az-hop
- in the config.yml change cvmfs_eessi.enabled to false
- rerun ./install.sh

**Comment by shashankms9** [comment]
When i reinstated the new deployment i am facing another issue in telegrap deployment got failed with the below error.

fatal: [ccportal]: FAILED! => {"changed": false, "changes": {"installed": ["telegraf-1.18.2-1"]}, "msg" : "warning: /var/cache/yum/x86_64/7/influxdb-stable/packages/telegraf-1.18.2-1.X8664.rpm: Header V4 RS A/SHA512 Signature, key ID 7df8b07e: NOKEY\nImporting GPG key 0x2582E0C5:\n Userid : V'InfluxDB Pac kaging Service <support@influxdb.com>\"\n Fingerprint: 05ce 1508 5fc0 9dl8 e99e fb22 684a 14cf 2582 eOc 5\n From	: https ://repos.influxdata.com/influxdb.key\n\n\nPublic key for telegraf-1.18.2-1.x86_64
.rpm is not installed\n\n\n Failing package is: telegraf-1.18.2-1.x86_64\n GPG Keys are configured as: https://repos.influxdata.com/influxdb.key\n\n", "rc": 1, "results": ["Loaded plugins: langpacks\nResolv ing Dependencies'^--> Running transaction check\n—> Package telegraf.x86_64 0:1.18.2-1 will be install

Find the screenshots below:

![image](https://user-images.githubusercontent.com/104433795/218072836-229fbda8-895e-4b1c-87e2-8cf2cb5e10f2.png)

![image](https://user-images.githubusercontent.com/104433795/218072862-bb2e792f-8361-4a79-90e6-d08aab17ac44.png)

![image](https://user-images.githubusercontent.com/104433795/218073124-ff806b07-2f9d-4d08-b9ad-6ae5966768d4.png)

**Comment by xpillons** [comment]
You can temporarily ignore that error due to key rotation being made by Telegraf. This is already fixed in the main branch which should be released soon.
This shouldn't impact the next steps of the tutorial.
