### ISSUE TITLE
vscode server startup failing as non-admin user

### ISSUE THREAD

**Issue by bmoxon** [Azure/az-hop#1330]
/area interactive

## Incorrect Behavior

Bringup of vscode server through Interactive sessions as an unprivileged user (e.g. hpcuser) fails.
The interactive session dialog shows "Starting" for 10+ minutes, then finally shows as "Complete" but never brings up the buttons for the node and "Connect to VScode", and the node shuts down.

Same operations work fine under adminuser.

@xpillons reports curl-downloaded script is doing a sudo, for which non-admin users are not configured.

+ mv ~/.cache/code-server/code-server-4.8.3-amd64.rpm.incomplete ~/.cache/code-server/code-server-4.8.3-amd64.rpm
+ sudo rpm -U ~/.cache/code-server/code-server-4.8.3-amd64.rpm

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified

## Steps to Reproduce the Problem

deployment: slurm scheduler, standard (centos79) image on compute nodes

* Start a vscode server as hpcuser (or other non-admin user)
* select execute node
* "card" will show Starting, then move to Complete without providing buttons for the node or to "Connect to VS Code"
* checking the slurm scheduler shows execute node running, then shutting down after 10-15 min

**Comment by xpillons** [comment]
The standalone option should be used when installing codeserver in `playbooks/roles/ood-applications/files/bc_codeserver/template/script.sh.erb`
