### ISSUE TITLE
Paraview App : Dynamic widget are missing

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1342]
When selecting viz3d that would require the whole node.
Please have a look at the data-* properties in the bc_ansys_workbench app for reference.

**Comment by utkarshayachit** [comment]
I dug into this a little and I am not sure this is necessary. Why are we locking the whole node when another non-GPU needing job could in theory run on the allocated node if we don't want to utilize it fully? `--gpus=...` will ensure that on other GPU requiring job will be allocated to that node (unless of course the node has more GPUs than we need).
