### ISSUE TITLE
Issue in Exercise 5 Task 4

### ISSUE THREAD

**Issue by shashankms9** [Azure/az-hop#1349]
## In what area(s)?

Exercise 5 Task 4 Create a case file and launch ParaView

## Expected Behavior

[Exercise 5 Task 4 Step 7](https://github.com/Azure/az-hop/blob/pipelines/docs/tutorials/quickstart.md#task-4-visualize-the-motorbike-tutorial-result) touch ~/motorbike/case. Foam as per the instruction command should run successfully. 

## Actual Behavior

Even though we created Modules modulefiles  in the cloud server we are not able to find the file on the Linux desktop server it as throwing a following **error touch ~/motorbike/case.foam
touch: cannot touch '/home/clusteradmin/motorBike/case.foam': No such file or directory**  

Have attached the screenshot below for reference.

![image](https://user-images.githubusercontent.com/104433795/219397362-5e9e6562-3510-4ad3-a5e7-11624e188181.png)

**Comment by xpillons** [comment]
have you proceed successfully the Exercice 5 tasks 1 to 4 ? these creates the ~/motorBike folder and content to view.

**Comment by shashankms9** [comment]
Yes I have able perform all the task in ex 5without any issue

**Comment by xpillons** [comment]
ok, so make sure that the tasks were using the users home directory to copy the motorBike case.
What is the content of your home dir ?

**Comment by shashankms9** [comment]
I was using same location as mentioned in the instructions

**Comment by xpillons** [comment]
can you run these commands :
cd
ls -alt

**Comment by xpillons** [comment]
got it your home directory is set to /home while it should be on /anfhome

**Comment by xpillons** [comment]
Can you please try to rerun the whole exercice using $HOME instead of ~ ? if that solve this issue I will fix the instructions.

**Comment by shashankms9** [comment]
I am currently out of my shift. Can i let you know tomorrow?

**Comment by xpillons** [comment]
sure

**Comment by shashankms9** [comment]
is there any command to set the path to $HOME

**Comment by shashankms9** [comment]
when i try to deploy the motorbike folder in anfhome and home directory I am facing an error with cannot create a directory.

Have attached the screenshot below for reference.

![image](https://user-images.githubusercontent.com/104433795/219571148-278dda33-91ef-489f-8279-8bf25275f771.png)

![image](https://user-images.githubusercontent.com/104433795/219571172-e43b2210-6e4a-4198-b26a-fa852f63737e.png)

**Comment by xpillons** [comment]
Please change directory to your home directory with this command : cd
to confirm enter : pwd
both /home and /anfhome are the roots for users home directory. in your case your home directory is /anfhome/clusteradmin

**Comment by shashankms9** [comment]
i was able to do it for motorbike from above page but in Ex 6 task 4 when we try to open the file case. Foam in ParaView it has been throwing an error 

```
ERROR: In /builds/gitlab-kitware-sciviz-ci/build/superbuild/paraview/src/VTK/IO/Geometry/vtkOpenFOAMReader.cxx, line 11325
vtkPOpenFOAMReader (0x17e440a0): /anfhome/clusteradmin/drivaerFastback/case.foam contains no meshes.

ERROR: In /builds/gitlab-kitware-sciviz-ci/build/superbuild/paraview/src/VTK/Common/ExecutionModel/vtkExecutive.cxx, line 753
vtkPVCompositeDataPipeline (0x1814ddf0): Algorithm vtkPOpenFOAMReader(0x17e440a0) returned failure for request: vtkInformation (0x1814ae90)
  Debug: Off
  Modified Time: 384683
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_INFORMATION
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0
```

Have attached the screenshot below for reference.

![image](https://user-images.githubusercontent.com/104433795/219639936-1c624dfc-6ec0-494e-9717-55455667b781.png)

![image](https://user-images.githubusercontent.com/104433795/219640217-f78d18aa-22a3-4f10-809a-ae81dff73537.png)

**Comment by xpillons** [comment]
I don't see any log files so I guess your job didn't run successfully. Have you done all tasks from Ex6 before ?

**Comment by shashankms9** [comment]
yes i have fallowed the each and every steps

**Comment by xpillons** [comment]
please try again as there are no job logs, there is an error somewhere

**Comment by shashankms9** [comment]
after reperforming the steps also i am not able to see any log files 

![image](https://user-images.githubusercontent.com/104433795/219654496-c57d88b0-660a-42d0-935b-c88ce987a044.png)

**Comment by xpillons** [comment]
ok please replace the ~ in the instructions by $HOME
It sound that ~ is refering to /home instead of /anfhome hence the errors

**Comment by shashankms9** [comment]
actually i am using /anfhome these directory only

**Comment by shashankms9** [comment]
Hi @xpillons is there any work around for these

**Comment by xpillons** [comment]
please replace all ~ with /home/clusteradmin in all commands

**Comment by shashankms9** [comment]
My environment is not working as expected due to a deployment issue, as I re-deploy it.

**Comment by shashankms9** [comment]
When we try to run the command in Linux VM I'm facing an issue. Do you have any idea why we are facing these issues?

![image](https://user-images.githubusercontent.com/104433795/220842363-79483b43-b797-4312-b508-63ba195d0452.png)

**Comment by xpillons** [comment]
It seems that you are working on the main branch.
Please make sure to use version 1.0.29 as documented in the quickstart tutorial https://azure.github.io/az-hop/tutorials/quickstart.html

**Comment by shashankms9** [comment]
we are using this command for deploy, ./deploy.sh azhop_quickstart <location> v1.0.29 
ex: ./deploy.sh azhop_quickstart1 eastus v1.0.29

**Comment by xpillons** [comment]
ok it look like the branch name is not taken in account in cloud-init. Let me have a look

**Comment by xpillons** [comment]
The workaround to fix this is to edit on cloudshell the file <azhop_root>/deploy/install.sh
Change line 14 from 
`git clone --recursive https://github.com/Azure/az-hop.git
`
to 
`git clone --recursive https://github.com/Azure/az-hop.git -b v1.0.29
`

**Comment by shashankms9** [comment]
thank you

**Comment by xpillons** [comment]
oops, wrong directory it should be in <azhop_root>/deploy/resource/install.sh

**Comment by shashankms9** [comment]
is these issue has been resolved

**Comment by xpillons** [comment]
yes instructions are now updated

**Comment by shashankms9** [comment]
now the deployment is working fine

**Comment by xpillons** [comment]
I will close the issue then
