### ISSUE TITLE
SLURM : Uppercase queue name are not allowed

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1354]
## Version
1.0.33

Provisioning node will always failed in CC with error "Hostname not registered yes in DNS" => fix is to upgrade to CC for Slurm version 2.7.1

**Comment by ltalirz** [comment]
Note that https://github.com/Azure/az-hop/pull/1353 enforces lowercase queue names.

Please relax this constraint in the schema once the upgrade is applied
