### ISSUE TITLE
Quota issue for Standard_NV6

### ISSUE THREAD

**Issue by shashankms9** [Azure/az-hop#1381]
There is a limited quota for **Standard_NV6 SKU**, so we cannot deploy the required SKU in bulk. In addition, we have raised a support ticket with Microsoft, but we have been informed that they are unable to approve it. 

As this is delaying our project could you please prioritize and provide a workaround as soon as possible?

**Comment by xpillons** [comment]
You can instead use the Standard_NV12s_v3, you may request quota for the NVs_v3 family.
Then once quota has been approved, on the deployer VM edit the config.yml file to change this line :
`vm_size: Standard_NV6
`
by

`vm_size: Standard_NV12s_v3
`

Then rerun the cccluster playbook
`./install.sh cccluster
`

**Comment by shashankms9** [comment]
My apologies, we have raised the quota for both the NVs_V3 family and the NV family.

**Comment by xpillons** [comment]
Ok so then you may try with NC8as_T4_v3.

**Comment by shashankms9** [comment]
can you provide which and all SKUs we can use?

**Comment by xpillons** [comment]
for GPU acceleration our image support these families : NV, NVs_v3, NC_T4_v3
