### ISSUE TITLE
MariaDB Root CA must be rotated in March 2023

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1424]
## Version
1.0.33

This is impacting : 
- SLURM Accounting on the `scheduler` VM
- Guacamole service on the `ondemand` VM
- Guac Spooler on the `guacamole` VM

# Certificate rotation for Azure Database for MariaDB

Clients' devices using SSL to connect to Azure Database for MariaDB instances must have their CA certificates updated. To address compliance requirements, starting March 2023 the CA certificates were changed from BaltimoreCyberTrustRoot to DigiCertGlobalRootG2. If any of your client applications are pinned to the root CA Baltimore CyberTrust Root, immediate action is required to prevent disruption to your connectivity to Azure Database for MariaDB. 
## Required action 
To avoid interruption of your application's availability as a result of certificates being unexpectedly revoked, or to update a certificate that has been revoked, follow the steps explained [here](https://learn.microsoft.com/en-us/azure/mariadb/concepts-certificate-rotation). 

## More information 
You need to create a new .pem file, which combines the current certificate and the new one. During the SSL certificate validation, one of the allowed values will be used. In the future, after the new certificate is deployed on the server side, you can change your CA .pem file to DigiCertGlobalRootG2.crt.pem. 
For more details, please see [Understanding the changes in the Root CA change for Azure Database for MariaDB.](https://learn.microsoft.com/en-us/azure/mariadb/concepts-certificate-rotation)

**Comment by ltalirz** [comment]
@xpillons Could you please comment in which cases action is needed by az-hop admins on this?

**Comment by xpillons** [comment]
That would be needed when you use MariaDB for the SLURM accounting.
