### ISSUE TITLE
viz & viz3d images based on Alma

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1440]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Describe the feature
We're starting to use the Alma 8.7 images (partly due to the newer linux kernel needed for user-space overlayfs via enroot).

Currently, the viz, viz3d images are not yet ported to alma, resulting in a different environment (e.g. conda packages with compiled binaries can break, etc.).

It would be great to be able to move to alma completely

**Comment by edwardsp** [comment]
Initial version published in the marketplace.  Use the following image: azhpc:azhop-desktop:almalinux-8_7:latest

The packer script is in feature/alma87desktop branch
