### ISSUE TITLE
Keyvault soft delete causes problems with TF deployments

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#1443]
## Version
Please provide the azhop version used, this one is located in the bottom right of the homepage, or the version you checkout from. 
git commit: 01b1a812d5a0617e73c3914c691107f48489a067

## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
 /area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Expected Behavior

If you delete a resource group and then create a new deployment in the same RG, there should be no issues.

## Actual Behavior

Resource group soft deletion policy means the resource ID isn't truly gone. TF complains about unimported state and generates errors. You have to wait 7 days to truly delete a keyvault, or manually import each resource back into terraform.

Soft delete will become mandatory on all keyvaults in 2025: https://learn.microsoft.com/en-us/azure/key-vault/general/soft-delete-change

## Steps to Reproduce the Problem

- Create an azhop deployment with soft delete keyvault turned on (in tf/keyvault.tf)
- Delete resource group
- Recreate deployment with same resource group name
- Tf complains about existing keyvault.

A possible solution here would be to randomize the keyvault names on creation and not simply hash them based on the RG name.

**Comment by xpillons** [comment]
@matt-chan in fact the unique name is based on the RG name, and if we change that, it means that a new name will be generated each time you do a new deployment, recreating the KV.
The workaround is to manually purge the KV. We are working on a companion script to remove these resources, it's actually located in `deploy/purebicep/cleanup.sh`

**Comment by matt-chan** [comment]
Thank you for the tip about the cleanup script! I'll give it a try.

**Comment by ltalirz** [comment]
> @matt-chan in fact the unique name is based on the RG name, and if we change that, it means that a new name will be generated each time you do a new deployment, recreating the KV. 

Can you elaborate why this is a problem?

If a new deployment wants to reuse the keyvault of a previous deployment, could one not just refer to it in the `config.yml`?

> The workaround is to manually purge the KV. We are working on a companion script to remove these resources, it's actually located in `deploy/purebicep/cleanup.sh`

If I read [here](https://stackoverflow.com/a/74207581) correctly, then purging a soft-deleted keyvault requires owner permissions.
Matt's use case is relevant in cases where our permissions are limited (which is why we want to stay in the same resource group), i.e. we are unlikely to have owner privileges.

**Comment by xpillons** [comment]
This PR #1544 will allows you to provide a name for the KeyVault and few other resources, so this should allows you to specify a new random one when you want.

**Comment by ltalirz** [comment]
That's great, thanks Xavier!

@matt-chan I believe this issue can be closed
