### ISSUE TITLE
apptainer init failed on ubuntu 18.04

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1461]
## Version
1.0.34+

![image](https://user-images.githubusercontent.com/7349410/230462793-bf8e1479-689d-4121-a631-72d3f5d0a8a7.png)

**Comment by JingchaoZhang** [comment]
I cannot replicate this issue. ubuntu 2004 
![image](https://user-images.githubusercontent.com/6353250/230497782-06873df0-6355-4a2a-909d-8b1cb4e6c0d8.png)

**Comment by xpillons** [comment]
Please try with ubuntu 18.04 as per the issue description
