### ISSUE TITLE
Terraform Subnet State not Imported

### ISSUE THREAD

**Issue by thielen24** [Azure/az-hop#1488]
## Version
1.0.34

## In what area(s)?
/area administration
/area configuration

## Expected Behavior
Deploy via build.sh imports necessary state based on config.yml options.

## Actual Behavior
Deploy via build.sh fails to associate the created network security groups with existing subnets:

Error: A resource with the ID "...subnetid" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_subnet_network_security_group_association" for more information.
│
│   with azurerm_subnet_network_security_group_association.frontend[0],
│   on network_security_group.tf line 75, in resource "azurerm_subnet_network_security_group_association" "frontend":
│   75: resource "azurerm_subnet_network_security_group_association" "frontend" {

This error occurs for every azurerm_subnet_network_security_group_association block in network_security_group.tf, lines 75-93.

## Steps to Reproduce the Problem
Attempt to deploy Azure HPC OnDemand infrastructure with build.sh using existing subnets and create_nsg true, such as the following config.yml settings:

network:
  create_nsg: true
  vnet:
    id: "vnet id"
    address_space: "vnet address space"
    subnets:
      frontend:
        name: nameofexistingsubnet
        create: false
      admin:
        name: nameofexistingsubnet
        create: false
      netapp:
        name: nameofexistingsubnet
        create: false
      ad:
        name: nameofexistingsubnet
        create: false
      compute:
        name: nameofexistingsubnet
        create: false

**Comment by thielen24** [comment]
I believe the cause of this error might be related to the fact that our subnets already exist, but in a different resource group than specified on line 9 of the config.yml.

**Comment by xpillons** [comment]
Os, so if you provide the whole vnet/subnets you will have to manage the NSGs by yourself. Is there a specific reason why you are providing all the subnets ?

**Comment by thielen24** [comment]
The vnet/subnets are created in advance by another user in a separate resource group (same subscription) dedicated to networking. The reason is due to our corporate Cybersecurity/RBAC architecture and policies, which defaults to least privilege. Currently, we are trying to deploy az-hop with fewer permissions than specified in the "Azure Pre-requisites" and are requesting of our cybersecurity additional permissions when we understand the specific ones that are lacking. 

Based on the error messages, the lack of terraform state for the subnets seems to be related to the use of two resource groups, rather than a permission issue. Any ideas for what would need to be modified in the terraform to get the networking resource group state incorporated?

**Comment by thielen24** [comment]
Alright, I am better understanding the problem after some more testing. I believe the errors I'm getting are because NSGs already exist associated with the subnets. Setting "create_nsg" to false fixes the errors, but also forces you to use predefined asgs. I'm hoping to use the existing NSGs and have az-hop create the ASGs and will look into making that change. I'll close this issue for now.

**Comment by xpillons** [comment]
Thanks
