### ISSUE TITLE
pyxis/enroot config failure

### ISSUE THREAD

**Issue by egmsft** [Azure/az-hop#1539]
## Version
1.0.34

## In what area(s)?
 /area ansible

## Expected Behavior
Configured az-hop with a basic terraform deployment using slurm as the queue manager. I also disabled lustre and monitoring/alerting.  Considering the basic setup, I expected a successful deployment and configuration of az-hop. 

## Actual Behavior
az-hop failed during the configuration step. Specifically, az-hop reached a failure while executing the Build Pyxis task from: 
./playbooks/roles/slurmserver/tasks/pyxis.yml. The error reported by the task is the following: 

TASK [slurmserver : Build Pyxis] *******************************************************************************************************************************************************
Monday 22 May 2023  18:21:27 +0000 (0:00:01.836)       0:03:09.305 ************ 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
fatal: [scheduler]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.0.0.21 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/
hpcadmin/.ansible/tmp/ansible-tmp-1684779687.9801753-39019-160007044101435/AnsiballZ_make.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/hpcadmin/.ansible/tmp/a
nsible-tmp-1684779687.9801753-39019-160007044101435/AnsiballZ_make.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/hpc
admin/.ansible/tmp/ansible-tmp-1684779687.9801753-39019-160007044101435/AnsiballZ_make.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib6
4/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mo
d_loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_make_payload_fiQqWS/ansible_make_payload
.zip/ansible_collections/community/general/plugins/modules/make.py\", line 233, in <module>\r\n  File \"/tmp/ansible_make_payload_fiQqWS/ansible_make_payload.zip/ansible_collections/co
mmunity/general/plugins/modules/make.py\", line 228, in main\r\n  File \"/usr/lib64/python2.7/pipes.py\", line 269, in quote\r\n    for c in file:\r\nTypeError: 'NoneType' object is no
t iterable\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

The failure of this task prevented the successful configuration of az-hop. To get past this issue I had to disable the pyxis installation/setup on both the slurm server and clients. However, this should not fail for those deployments that do require the use of containers. 

## Steps to Reproduce the Problem

Deploy az-hop with these config settings: 
 log_analytics: 
    create: false 
alerting:                                                                          
    enabled: false

lustre section commented out - since setting it to false is somehow ignored 

 queue_manager: slurm 

all queues spot option set to false

the deployment should be successful, but the install will fail at the build pyxis task.

**Comment by xpillons** [comment]
closed as duplicated with #1481 fixed by PR #1485
