### ISSUE TITLE
Allow multiple mod-rewrite domains

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#1554]
Hi @xpillons,

It would be useful to allow multiple domain names in the mod-rewrite conditions for ood-portal.yml.

We are moving to a private link deployment model (less issues with VPN subnet clashes) and we often have two or more private endpoints pointing to the OOD VM. The user accesses OOD directly with the private endpoint IP. The current setup rewrites the URL to what is detected during the configuration step. That IP is inaccessible so the rewrite rule actually breaks the setup. It also doesn't work when we have more than 1 FQDN.

If we could make 
```
# ood-portal.yml

RewriteCond %{HTTP_HOST} !^(__FQDN__(:443)?)?$ [NC]
```

become:
```
RewriteCond __FQDN1__ !^(__FQDN1__(:443)?)?$ [NC]
...

RewriteCond __FQDN2__ !^(__FQDN2__(:443)?)?$ [NC]
...
```
and then read FQDN1 and FQDN2 from the config.yml, I think this would solve the problem for us? 

I'm not familiar enough with `Header always set Content-Security-Policy` to know what to do there though.

Thank you!
Matt

cc @ltalirz

**Comment by xpillons** [comment]
can't you use correct name resolution and have your client resolving the same name with different IPs ?
I would also ask this kind of question to https://discourse.openondemand.org/

**Comment by matt-chan** [comment]
Yes I think so. I haven't been able to figure out how to make this work yet though. I'll message in the channel!

**Comment by ltalirz** [comment]
Coming back to this issue, for the HTTP redirect rule, the generic solution is simple:
```
<VirtualHost *:80>
  RewriteEngine On
  RewriteRule ^(.*) https://%{HTTP_HOST}$1 [R=301,NE,L]
</VirtualHost>
```

For the SSL hosts it is a little more involved since the FQDN appears in many places.
The easiest way is probably [using `mod_macro`](https://serverfault.com/a/556178), something like (untested)
```
<Macro VHost $domain>
<VirtualHost *:443>
  ServerName $domain
  ServerAlias www.$domain

  ErrorLog  "/var/log/httpd24/$domain_error_ssl.log"
  CustomLog "/var/log/httpd24/$domain_access_ssl.log" combined

  RewriteEngine On
  RewriteCond %{HTTP_HOST} !^$domain(:443)?$ [NC]
  RewriteRule ^(.*) https://$domain$1 [R=301,NE,L]

  # Support maintenance page during outages of OnDemand
  RewriteEngine On
  RewriteCond /var/www/ood/public/maintenance/index.html -f
  RewriteCond /etc/ood/maintenance.enable -f
  RewriteCond %{REQUEST_URI} !/public/maintenance/.*$
  RewriteRule ^.*$ /public/maintenance/index.html [R=302,L]

  Header always set Content-Security-Policy "frame-ancestors https://$domain;"
  Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"

  SSLEngine On
  SSLCertificateFile "/etc/ssl/$domain/$domain.crt"
  SSLCertificateKeyFile "/etc/ssl/$domain/$domain.key"
</VirtualHost>
</Macro>
```

You can then
```
Use VHost example.com
Use VHost 10.92.4.3
```

**Comment by xpillons** [comment]
Have you reach out to the OOD team ? If not I would suggest, and potentially suggest a PR. This could be useful for the community too.

**Comment by ltalirz** [comment]
should be supported by OOD 3 https://github.com/OSC/ood-ansible/issues/191#issuecomment-1581100310

**Comment by xpillons** [comment]
another good reason to upgrade on OOD 3 as per #1460
