### ISSUE TITLE
Update cyclecloud-slurm version to 3.x

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1623]
## Describe the feature
This means :
- slurm 22.05+ is the minimum release
- updates on the slurm installation and configuration

Document how to migrate from 20 to 22

Migrate from 2.7.x to 3.0.1 see https://github.com/Azure/cyclecloud-slurm/tree/3.0.1

**Comment by ltalirz** [comment]
I opened a thread on the topic of node allocation logic with SLURM

> SLURM can be configured to allow multiple jobs to share the same node.
> For example, 2 jobs can run on 60 cores each of a HB120 VM. 
> When the VM is already allocated before the jobs are submitted, then SLURM will happily place the two jobs on the same node.
> However, when the nodes are not yet allocated from Azure, SLURM (via CycleCloud) will end up pulling two HB120 VMs from Azure, one for each job.

and Kai Neuffer said
> a customer of mine has a similar issue but for me it works fine with CC 8.4.0 and the Slurm 3.0.1 template.

So this may be another reason to try this upgrade
