### ISSUE TITLE
Unauthorized to access CycleCloud dashboard when using single sign on with AAD

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1669]
## Version
v1.0.35

## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
/area ood
> /area remote-visualization
> /area user-management

## Expected Behavior
When logging into Open OnDemand using OpenID connect with Azure AD, I am able to navigate to the CycleCloud dashboard.

## Actual Behavior

When logging into Open OnDemand using OpenID connect with Azure AD, I get "Unauthorized access" when clicking on the "Azure CycleCloud" link for the CycleCloud dashboard.

Note: It's possible that this works in some circumstances, just in the cases I've tried I've never been able to get it to work despite me having matching users on the AZ-HOP internal AD service and the OIDC login to the rest of the OnDemand portal working fine.

## Investigation

This comes from the OOD Apache configuration, which uses local PAM rather than OIDC to authenticate the user
```
  <Location "/cyclecloud">
    AuthType Basic
    AuthName "Open OnDemand"
    AuthBasicProvider PAM
    AuthPAMService ood
    Require valid-user


ProxyPass http://ccportal:80/cyclecloud
    ProxyPassReverse http://ccportal:80/cyclecloud
  </Location>
```

Besides being broken in my case, I think this is also a security concern, since using `https://<ondemand-url>/cyclecloud` bypasses the OpenID connect authentication, which can provide much stronger guarantees than basic Auth (e.g. it may require you to be on a machine controlled by the Azure AD tenant, etc.).

As a workaround, I can get this to work by replacing the above section with
```
  <Location "/cyclecloud">
    AuthType openid-connect
    Require valid-user

ProxyPass http://ccportal:80/cyclecloud
    ProxyPassReverse http://ccportal:80/cyclecloud
  </Location>
```

In this case, /cyclecloud still requires authentication with openid connect.
Once the cyclecloud portal is reached, the user then needs to log in with the password of their local AD account.

## Steps to Reproduce the Problem

1. Set up AZ-HOp for login via OpenID connect via Azure AD
2. Click on the CycleCloud dashboard link

**Comment by ltalirz** [comment]
@xpillons can you reproduce this bug?

Is there a solution for access to the CycleCloud dashboard in the case of single sign-on?

**Comment by xpillons** [comment]
The workaround is to use the basic credentials to connect to CycleCloud which will authenticate against the local AD.
