### ISSUE TITLE
reintroduce azure cli to Alma images?

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1687]
## In what area(s)?

/area image

## Describe the feature
Hi, I notice that the alma images no longer seem to have the azure cli, which used to be present on CentOS

```
$ cd packer
$ git grep azure-cli
scripts/centos/linux-setup.sh:echo -e "[azure-cli]
scripts/centos/linux-setup.sh:baseurl=https://packages.microsoft.com/yumrepos/azure-cli
scripts/centos/linux-setup.sh:gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/azure-cli.repo
scripts/centos/linux-setup.sh:yum install -y azure-cli
```

Is this on purpose?

The azure cli is sometimes useful also on the nodes

**Comment by xpillons** [comment]
azcli was never in our centOS image, it must have been in your forked repo

```
~/repos/Azure/az-hop/packer$ git grep azure-cli
~/repos/Azure/az-hop/packer$ 
```

**Comment by ltalirz** [comment]
ah, sorry about that - you are right.

in that case we keep it on our side
