### ISSUE TITLE
create_passwords script fails (no vault?), perhaps due to missing file

### ISSUE THREAD

**Issue by mkbane** [Azure/az-hop#1692]
## Version
I did a git clone at approx 19:20 BST today 28 Sept 2023.

$ git clone --recursive https://github.com/Azure/az-hop.git
Cloning into 'az-hop'...
remote: Enumerating objects: 23668, done.
remote: Counting objects: 100% (4839/4839), done.
remote: Compressing objects: 100% (678/678), done.
remote: Total 23668 (delta 4183), reused 4619 (delta 4084), pack-reused 18829
Receiving objects: 100% (23668/23668), 10.64 MiB | 5.05 MiB/s, done.
Resolving deltas: 100% (15982/15982), done.
Submodule 'playbooks/roles/ood-ansible' (https://github.com/OSC/ood-ansible.git) registered for path 'playbooks/roles/ood-ansible'
Cloning into '/home/mkb/az-hop/playbooks/roles/ood-ansible'...
remote: Enumerating objects: 1561, done.
remote: Counting objects: 100% (488/488), done.
remote: Compressing objects: 100% (219/219), done.
remote: Total 1561 (delta 372), reused 297 (delta 261), pack-reused 1073
Receiving objects: 100% (1561/1561), 290.48 KiB | 1.71 MiB/s, done.
Resolving deltas: 100% (909/909), done.
Submodule path 'playbooks/roles/ood-ansible': checked out '12995d36f4fde2fb5839e50664521e4bd39bd0c0'

## In what area(s)?

> /area administration
> /area ansible
> /area configuration
> /area documentation

## Expected Behavior

The tutorial at https://azure.github.io/az-hop/tutorials/quick_install.html#quick-installation-guide in Task 6 says to run ./create_passwords.sh but actually fails:

## Actual Behavior

$ ./create_passwords.sh
Error: open playbooks/group_vars/all.yml: no such file or directory
Keyvault retrieved from playbooks/group_vars/all.yml is empty

There is no group_vars dir within playbooks. If I create empty dir or even empty group_vars/all.yml the command still fails/gives errors

**Comment by xpillons** [comment]
You need to build your environment first before applying this script. the missing files will be created by the build command.

**Comment by mkbane** [comment]
As per tutorial, the step before ./create_passwords.sh was 
./build.sh -a plan -l bicep

**Comment by xpillons** [comment]
great. Have you run `./build.sh -a apply -l bicep` ? this command is the one creating these resources. The plan one is to check configuration is correct and will list what will be created.

**Comment by mkbane** [comment]
My mistake, I had missed the "apply" command (from step1 of Task6). However, when I do that know I get this long error:

mkb@ASN-ACA7353:~/az-hop$ ./build.sh -a apply -l bicep
Activating conda environment
ok -- validation done
config.yml passes validation
 - logged in Azure with User 55142816@ad.mmu.ac.uk
* Deploying using Bicep
/home/mkb/az-hop/bicep/mariadb.bicep(36,30) : Warning use-resource-symbol-reference: Use a resource reference instead of invoking function "reference". This simplifies the syntax and allows Bicep to better understand your deployment dependency graph. [https://aka.ms/bicep/linter/use-resource-symbol-reference]

{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/providers/Microsoft.Resources/deployments/azhop_2023.0929.085400","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhop","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhop","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhopVmscheduler","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhopVmscheduler","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"NotFound","message":"Subscription not found."}]}]},{"code":"ResourceDeploymentFailure","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhopVmccportal","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhopVmccportal","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"NotFound","message":"Subscription not found."}]}]},{"code":"ResourceDeploymentFailure","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhopVmad","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhopVmad","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"NotFound","message":"Subscription not found."}]}]},{"code":"ResourceDeploymentFailure","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhopVmgrafana","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhopVmgrafana","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"NotFound","message":"Subscription not found."}]}]},{"code":"ResourceDeploymentFailure","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhopVmjumpbox","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhopVmjumpbox","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"NotFound","message":"Subscription not found."}]}]}]}]}]}}

**Comment by xpillons** [comment]
Please confirm that your user account used to logged in on Azure is using the right subscription as listed on [Task4](https://azure.github.io/az-hop/tutorials/quick_install.html#task-4-login-in-azure).
Also check your user's permission as listed [here](https://azure.github.io/az-hop/tutorials/quick_install.html#task-1-validate-the-owner-role-assignment-in-the-azure-subscription)

**Comment by mkbane** [comment]
Hi, as you can tell, I'm fairly new to Azure sys admin logistics. I'm presuming something timed out (re az login) so have re-done Task 4 steps 1-3, then jumped back to Task 6, step 1 'apply' and now get a quota error (NB I'm using the free $200 azure trial):

mkb@ASN-ACA7353:~/az-hop$ ./build.sh -a apply -l bicep
Activating conda environment
ok -- validation done
config.yml passes validation
 - logged in Azure with User 55142816@ad.mmu.ac.uk
* Deploying using Bicep
/home/mkb/az-hop/bicep/mariadb.bicep(36,30) : Warning use-resource-symbol-reference: Use a resource reference instead of invoking function "reference". This simplifies the syntax and allows Bicep to better understand your deployment dependency graph. [https://aka.ms/bicep/linter/use-resource-symbol-reference]

{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/providers/Microsoft.Resources/deployments/azhop_2023.0929.111500","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhop","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/998dc91b-1656-4989-b13e-859e66197475/resourceGroups/azhop-resourcegroup-mkb/providers/Microsoft.Resources/deployments/azhop","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidTemplateDeployment","message":"The template deployment 'azhopVmjumpbox' is not valid according to the validation procedure. The tracking id is '520cbb00-f3a6-4beb-b463-d18738099b54'. See inner errors for details.","details":[{"code":"QuotaExceeded","message":"Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: uksouth, Current Limit: 4, Current Usage: 4, Additional Required: 2, (Minimum) New Limit Required: 6. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/#blade/Microsoft_Azure_Capacity/UsageAndQuota.ReactView/Parameters/%7B%22subscriptionId%22:%22998dc91b-1656-4989-b13e-859e66197475%22,%22command%22:%22openQuotaApprovalBlade%22,%22quotas%22:[%7B%22location%22:%22uksouth%22,%22providerId%22:%22Microsoft.Compute%22,%22resourceName%22:%22cores%22,%22quotaRequest%22:%7B%22properties%22:%7B%22limit%22:6,%22unit%22:%22Count%22,%22name%22:%7B%22value%22:%22cores%22%7D%7D%7D%7D]%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests"}]},{"code":"InvalidTemplateDeployment","message":"The template deployment 'azhopVmscheduler' is not valid according to the validation procedure. The tracking id is '30f3f900-3b46-4250-bcca-b7b82ff75b2a'. See inner errors for details.","details":[{"code":"QuotaExceeded","message":"Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: uksouth, Current Limit: 4, Current Usage: 4, Additional Required: 2, (Minimum) New Limit Required: 6. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/#blade/Microsoft_Azure_Capacity/UsageAndQuota.ReactView/Parameters/%7B%22subscriptionId%22:%22998dc91b-1656-4989-b13e-859e66197475%22,%22command%22:%22openQuotaApprovalBlade%22,%22quotas%22:[%7B%22location%22:%22uksouth%22,%22providerId%22:%22Microsoft.Compute%22,%22resourceName%22:%22cores%22,%22quotaRequest%22:%7B%22properties%22:%7B%22limit%22:6,%22unit%22:%22Count%22,%22name%22:%7B%22value%22:%22cores%22%7D%7D%7D%7D]%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests"}]},{"code":"InvalidTemplateDeployment","message":"The template deployment 'azhopVmad' is not valid according to the validation procedure. The tracking id is 'e0aa3160-9d97-485d-8524-42c7ad13d3a1'. See inner errors for details.","details":[{"code":"QuotaExceeded","message":"Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: uksouth, Current Limit: 4, Current Usage: 4, Additional Required: 2, (Minimum) New Limit Required: 6. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/#blade/Microsoft_Azure_Capacity/UsageAndQuota.ReactView/Parameters/%7B%22subscriptionId%22:%22998dc91b-1656-4989-b13e-859e66197475%22,%22command%22:%22openQuotaApprovalBlade%22,%22quotas%22:[%7B%22location%22:%22uksouth%22,%22providerId%22:%22Microsoft.Compute%22,%22resourceName%22:%22cores%22,%22quotaRequest%22:%7B%22properties%22:%7B%22limit%22:6,%22unit%22:%22Count%22,%22name%22:%7B%22value%22:%22cores%22%7D%7D%7D%7D]%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests"}]},{"code":"InvalidTemplateDeployment","message":"The template deployment 'azhopVmgrafana' is not valid according to the validation procedure. The tracking id is 'bbb6f1dd-98fe-4ad1-b542-2a894a34df3b'. See inner errors for details.","details":[{"code":"QuotaExceeded","message":"Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: uksouth, Current Limit: 4, Current Usage: 4, Additional Required: 2, (Minimum) New Limit Required: 6. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/#blade/Microsoft_Azure_Capacity/UsageAndQuota.ReactView/Parameters/%7B%22subscriptionId%22:%22998dc91b-1656-4989-b13e-859e66197475%22,%22command%22:%22openQuotaApprovalBlade%22,%22quotas%22:[%7B%22location%22:%22uksouth%22,%22providerId%22:%22Microsoft.Compute%22,%22resourceName%22:%22cores%22,%22quotaRequest%22:%7B%22properties%22:%7B%22limit%22:6,%22unit%22:%22Count%22,%22name%22:%7B%22value%22:%22cores%22%7D%7D%7D%7D]%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests"}]},{"code":"InvalidTemplateDeployment","message":"The template deployment 'azhopVmccportal' is not valid according to the validation procedure. The tracking id is 'b805aefe-7869-4ca8-842a-8658df892e17'. See inner errors for details.","details":[{"code":"QuotaExceeded","message":"Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: uksouth, Current Limit: 4, Current Usage: 4, Additional Required: 2, (Minimum) New Limit Required: 6. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/#blade/Microsoft_Azure_Capacity/UsageAndQuota.ReactView/Parameters/%7B%22subscriptionId%22:%22998dc91b-1656-4989-b13e-859e66197475%22,%22command%22:%22openQuotaApprovalBlade%22,%22quotas%22:[%7B%22location%22:%22uksouth%22,%22providerId%22:%22Microsoft.Compute%22,%22resourceName%22:%22cores%22,%22quotaRequest%22:%7B%22properties%22:%7B%22limit%22:6,%22unit%22:%22Count%22,%22name%22:%7B%22value%22:%22cores%22%7D%7D%7D%7D]%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests"}]}]}]}]}}
mkb@ASN-ACA7353:~/az-hop$

**Comment by mkbane** [comment]
hi, with the free Azure trial I do not have option to adjust quotas.
i am currently looking to eval Azhop as a method to set up virtual HPC cluster. I don't need to use significant resources but rather to understand the methods/options available.

Which makes me think I want to amend config to have fewer, smaller VMs (= virtual compute nodes?)

Can you, please, advise on an appropriate config.yml?

Yours, M

**Comment by xpillons** [comment]
let me build one simplified and push it in the repo. but at least you would need 3 VMs dual cores each.

**Comment by mkbane** [comment]
> Please confirm that your user account used to logged in on Azure is using the right subscription as listed on [Task4](https://azure.github.io/az-hop/tutorials/quick_install.html#task-4-login-in-azure). Also check your user's permission as listed [here](https://azure.github.io/az-hop/tutorials/quick_install.html#task-1-validate-the-owner-role-assignment-in-the-azure-subscription)

On this, I am using AZ free (which presume isn't a problem in and of itself?)

**Comment by mkbane** [comment]
> let me build one simplified and push it in the repo. but at least you would need 3 VMs dual cores each.

that would be most useful, please let me know when it's available. thanks in advance!
