### ISSUE TITLE
Users randomly getting 503 when hitting ondemand web portal

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1696]
## Version
1.0.37

## In what area(s)?

> /area ood

## Expected Behavior

Users should never get 503 error when hitting ondemand landing page

## Actual Behavior

Under certain circumstances, users get a 503 error when loading the ondemand landing page.
This can coincide with another user being able to use the page just fine.

After some investigation, @matt-chan figured out that the issue occurs in conjunction with single sign-on 
https://discourse.openondemand.org/t/hitting-max-authorized-valid-state-cookies/667
(it affects all az-hop installations with AAD single sign-on).

There is a default limit of how many active valid state cookies a user can have (7), and by default the user will not be able to create more.

This issue is difficult to debug, since it will be gone after the server is reset, and it will only affect "power users" who actually create >7 valid state cookies.

The fix is described in the link above.
In principle, the fix is already present in ood-ansible 2.0.6 (they have a variable `oidc_state_max_number_of_cookies` that defaults to `10 true`), but az-hop overwrites the `ood_auth_openidc`, so this default setting never ends up in the apache configuration (note: it may be worth changing this practice in any case; there may be similar cases of overlooked default values in the future) 

```
[root@ondemand ~]# cd /opt/rh/httpd24/root/etc/httpd/conf.d/                     
[root@ondemand conf.d]# grep OIDCState *
[root@ondemand conf.d]#
```

**Comment by ltalirz** [comment]
Apparently it is difficult to set this value via the `ood_auth_openidc` dictionary - using `"10 true"` results in '10 true' in the config file, which does not work.
Also "[10, true]" does not work.

**Comment by ltalirz** [comment]
opened https://github.com/OSC/ood-ansible/issues/211

**Comment by ltalirz** [comment]
@matt-chan later encountered even further issues of the form "Bad Request", which seems to be caused by cookies growing too large

Not sure whether this can be remedied, e.g. by reducing the number of concurrently active state cookies?

**Comment by xpillons** [comment]
I think there is another setting which can be used to define the maximum size of the cookie
