### ISSUE TITLE
Use Ephemeral OS on workers?

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#1697]
## In what area(s)?

> /area cyclecloud

## Describe the feature

Hi Xavier, 

I was looking at the Azure docs and noticed that we have ephemeral OS disks as an option for many VMs. Cyclecloud supports this since 7.7 I think. Is there a reason we don't use it on the workers by default? Cyclecloud claims it boots quicker, but I haven't checked closely

Thanks!
Matt

cc @ltalirz

**Comment by matt-chan** [comment]
I just verified. The workers start much faster with ephemeral OS. I can get a worker in about 6-9 minutes, as opposed to ~15 on regular disks.

**Comment by xpillons** [comment]
good suggestion, however ephemeral disks doesn't exists for all VM type; but we can add an option to enable it.
