### ISSUE TITLE
upgrade to latest azurehpc-health-checks release

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1807]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
/area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Describe the feature
This release adds health checks for NDv2 https://github.com/Azure/azurehpc-health-checks/issues/54#issuecomment-1885721500 (+ one more health check for nvlink)

**Comment by xpillons** [comment]
v0.27 provides lots of new features, it would need additional testings to confirm there are no side effects.
