### ISSUE TITLE
 GPG signature check filed, installing telegraf on ccportal

### ISSUE THREAD

**Issue by garvct** [Azure/az-hop#446]
I get the following error executing the telegraph ansible playbook

ansible-playbook -i playbooks/inventory ./playbooks/telegraf.yml

Looks like a GPG signature check filed, installing telegraf on ccportal.

fatal: [ccportal]: FAILED! => {
"changed": false,
"invocation": {
"module_args": {
"allow_downgrade": false,
"allowerasing": false,
"autoremove": false,
"bugfix": false,
"conf_file": null,
"disable_excludes": null,
"disable_gpg_check": false,
"disable_plugin": [],
"disablerepo": [],
"download_dir": null,
"download_only": false,
"enable_plugin": [],
"enablerepo": [],
"exclude": [],
"install_repoquery": true,
"install_weak_deps": true,
"installroot": "/",
"list": null,
"lock_timeout": 30,
"name": [
"https://dl.influxdata.com/telegraf/releases/telegraf-1.18.2-1.x86_64.rpm"
],
"releasever": null,
"security": false,
"skip_broken": false,
"state": "present",
"update_cache": false,
"update_only": false,
"validate_certs": true
}
},
"msg": "Failed to validate GPG signature for telegraf-1.18.2-1.x86_64"

**Comment by xpillons** [comment]
Look like this is a transient error. Can't be reproduced in our pipeline

**Comment by xpillons** [comment]
not reproducible after several pipeline runs
