### ISSUE TITLE
HTTPS certificate expired

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#450]
The certificate used for HTTPS connection has an expiration date of xx days. Once expired it's impossible to connect to the system. 
A refresh of the certificate should be scheduled or notified to the admin.

**Comment by xpillons** [comment]
## Solution
### Connect on the ondemand VM
delete certificate and configuration files 
```bash
./bin/connect hpcadmin@ondemand
sudo su -
rm -rf .getssl/
rm -rf /etc/ssl/ondemandrmgq2yjf.westeurope.cloudapp.azure.com/
rm -f /opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf
rm -rf /var/www/ood/.well-known
```

### Rerun the OOD playbook
```bash
install.sh ood
```

**Comment by matt-chan** [comment]
Hi @xpillons, 

These instructions don't work for our internal cluster. We delete the certificates but when we regenerate them, they come back with the same expiry date. Have you seen this before?

Thanks!
Matt

**Comment by xpillons** [comment]
Please check on the ondemand VM if the certificate files have been renewed in the /etc/ssl folder
Check for any getssl logs on /

**Comment by matt-chan** [comment]
Okay the renewal was successful! I'm not sure of the cause, sorry
