### ISSUE TITLE
[Epic] - Use an existing AD

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#475]
Instead of deploying a Sandbox ADDS dedicated to an azhop environment, provide the capability to connect to an existing Domain Controller.

- [ ] #1224
- [ ] #1223 
- [ ] #749 
- [ ] #1458

**Comment by lhg2** [comment]
Hi there - what is the ETA on integrating AzureHPC into existing AD/AAD? We have requirements to do this to meet strict security policies and have a tool by BeyondTrust (PowerBroker/ADBridge) to handle that integration. Can we 1) deploy that, and 2) disable the AD installation in the build script?

**Comment by xpillons** [comment]
@lhg2 we don't have an ETA yet and this work hasn't started. We are driven by customer requirements and demand, so if you have one we will be glad to work with you on this.
AAD being not supported by all building blocks we can't simply replace our DC by AAD, however AAD can be used for MFA after configuring OpenID Connect for the OnDemand portal. The need of a DC will remain to store users for the environment, and a mapping will be done using the email field provided by OIDC.

**Comment by lhg2** [comment]
Thank you. At the very least, we would need to use an AD integration tool (PowerBroker/ADBridge) to perform a domainjoin to our on-prem AD environment. We would need to bypass the current AD build requirement (don't need SSSD, etc.) and use our tooling for proper Enterprise integration and centralized user management. Is this achievable?

**Comment by xpillons** [comment]
probably yes, but never tested. You would have to replace in the scripts all the domain join stuff with yours. Also we do have specific groups used to grant users privileges for sudo access for example. Can we connect offline ? Please send me an email to xpillons@microsoft.com

**Comment by lhg2** [comment]
@xpillons - Yep! Thanks much.
