### ISSUE TITLE
job stayed queued while there are enough quota to run them

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#633]
3 jobs queued
Job974 : 8 HC44
Job975 : 3 HBv3
Job976 : 6 HBv3

Quota
	• HC44 is 500 cores or 11 nodes
	• HBv3 is 1024 cores or 8 nodes

those 3 jobs were waiting forever and no nodes were added.
we started a 2 HBv3 job, which trigger the autoscaler and 2 nodes were added.
as soon as this job was finished then new nodes were added for job 975

Version : v1.0.11

**Comment by brsiglar** [comment]
2 jobs queued both StarCCM
Job 1 - 3 HBv2
Job 2 - 3 HBv2

Quota 
HBv2 1200 cores or 10 nodes

The 2 multi-node jobs remained queued until a single node StarCCM job was submitted on an HBv2. As soon as the single node job was provisioned it went into a run state and the other 2 multi-node jobs in the queue also started running.

**Comment by xpillons** [comment]
Issue is coming from the autoscale library when using spot instance on the execute node array. Removing spot instance on execute is a workaround waiting for an official fix
