### ISSUE TITLE
.bashrc not called within a PBS job

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#699]
.bashrc is not called on compute nodes executing a PBS job

**Comment by xpillons** [comment]
Repro, create a script named foo.sh with this content
```
#!/bin/bash
printenv
```
This command will print all env variables including those in .bashrc
`qsub -l select=1 foo.sh`

This command will print all env variables **but not those** in .bashrc
`qsub -l select=1 -- foo.sh`

**Comment by edwardsp** [comment]
This is explained in section 2.3.4 in the PBS Pro [userguide](https://www.altair.com/pdfs/pbsworks/PBSUserGuide19.2.3.pdf):

![image](https://user-images.githubusercontent.com/905229/146410415-0ccc3d8a-a294-4167-8558-b935ad1754ff.png)
