### ISSUE TITLE
pre-commit missing in HPC Rover installation path?

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#835]
## In what area(s)?

/area administration
/area configuration

Maybe an "area deployment" would make sense?

## Expected Behavior

When following the deployment instructions, the HPC Rover docker container is started without errors.

## Actual Behavior

The console in VSCode showed

```
Running the postCreateCommand from devcontainer.json...

[229301 ms] Start: Run in container: /bin/sh -c cp -R /tmp/.ssh-localhost/* ~/.ssh && sudo chmod 600 ~/.ssh/* && sudo chown -R $(whoami) /hpc && git config --global core.editor vi && pre-commit install && pre-commit autoupdate
/bin/sh: 1: pre-commit: not found
[229525 ms] postCreateCommand failed with exit code 127. Skipping any further user-provided commands.
Done. Press any key to close the terminal.
```

I.e. `pre-commit` is missing (should be easy to fix)

## Steps to Reproduce the Problem

Follow the [recommended` deployment instructions](https://azure.github.io/az-hop/deploy/configure_toolchain.html).

**Comment by xpillons** [comment]
Can you please try to update the postCreateCommand by removing the offending pre-commit command in the .devcontainer/devcontainer.json and try to launch the container again ?

**Comment by xpillons** [comment]
Closing this issue as we have dropped the support of containers on a local desktop. Instead use a deployer VM or configure your local linux/wsl environement as documented.
