### ISSUE TITLE
build.sh -a plan failed due to command has been migrated to Microsoft Graph API

### ISSUE THREAD

**Issue by faister** [Azure/az-hop#876]
## In what area(s)?

/area configuration

## Expected Behavior

./build.sh -a plan should generate a Terraform deployment plan that includes a list of all resources to be provisioned

## Actual Behavior

Command failed, not able to continue.

### Task 2: Deploy Azure HPC OnDemand Platform infrastructure

1. Within the SSH session to the Azure VM, run the following command to generate a Terraform deployment plan that includes a list of all resources to be provisioned:

   ```bash
   ./build.sh -a plan
   ```
Then this error popped up.

WARNING: This command or command group has been migrated to Microsoft Graph API. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli
/azure/microsoft-graph-migration
ERROR: AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android,
 Mac, and Windows flavors.
Trace ID: c7b3c9b5-c3df-42cf-92d6-2f98e7d10e00
Correlation ID: 02c5f8fe-248e-4f9a-90a4-3fbb2c9c1d81
Timestamp: 2022-05-24 08:59:11Z
To re-authenticate, please run:
az login --scope https://graph.microsoft.com//.default
WARNING: This command or command group has been migrated to Microsoft Graph API. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli
/azure/microsoft-graph-migration
ERROR: AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android,
 Mac, and Windows flavors.
Trace ID: c7b3c9b5-c3df-42cf-92d6-2f98e7d10e00
Correlation ID: 02c5f8fe-248e-4f9a-90a4-3fbb2c9c1d81
Timestamp: 2022-05-24 08:59:11Z
To re-authenticate, please run:
az login --scope https://graph.microsoft.com//.default

Tried to self-mitigate by doing az login --scope https://graph.microsoft.com//.default --use-device-code but to no avail because our AAD Conditional Access policy does not support logging into MS Graph scope using Azure CLI.

**Comment by xpillons** [comment]
How did you logged in with az login ?
did you used a user account, a Service Principal Name or a Managed Identity ?

**Comment by xpillons** [comment]
latest main is now using az cli 2.37.0, please do a new test with that version.
