### ISSUE TITLE
Linux Desktop jobs without CPU are always on HOLD

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#905]
With OpenPBS, a session request to start a remote desktop without CPU is always queued.
qstat -fx <jobid> shows that while the slot_type=viz on the select statement is correct, the Resource_List.slot_type = viz3d which is wrong.
![image](https://user-images.githubusercontent.com/7349410/172802469-f2a8c933-69f2-46ad-a4eb-92a853cc0413.png)

**Comment by pkgudla** [comment]
In my case, when I changed the slot_type to "viz", remote desktop remains in queue forever....config.yml and queue stats in my case can be found in the issue "https://github.com/Azure/az-hop/issues/926". Any suggestions ?
