### ISSUE TITLE
Services distributed across separate VMs

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#943]
Besides the Lustre file system, which currently takes up the bulk of the always-on VM core count https://github.com/Azure/az-hop/issues/468, I am counting 6 separate virtual machines:

 - active directory
 - ondemand
 - grafana
 - scheduler
 - cyclecloud/ccportal
 - jumpbox

If I understand correctly, these VMs will be always-on, independent of their load, and I would guess that the average load of some of these machines on a typical cluster can be quite low (e.g. grafana, jumpbox?).
Is this an efficient use of computational resources?

In the context of containers, that can share computational resources, I do understand the reasoning behind distributing microservices across multiple container instances, but in the case of VMs I am wondering whether it is really necessary to have separate VMs for each of these services?

**Comment by xpillons** [comment]
Agree that this can be run in containers in the future with AKS for example.

**Comment by xpillons** [comment]
@ltalirz i would suggest to use the discussions feature of github instead of issues, I think it will be easier for the comunity to retrieve them.

**Comment by ltalirz** [comment]
Just mentioning that, on a small cluster, the Azure monitoring advisor recommends "shut down or resize your virtual machine" for the deployer, jumpbox, and scheduler.

**Comment by xpillons** [comment]
it's a false positive, as even of low activity is reported these VMs are critical.
