### ISSUE TITLE
docs: suggestions/questions concerning the `config.tpl.yml`

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#946]
The following are questions/suggestions concerning the `config.tpl.yml` as displayed [here](https://azure.github.io/az-hop/deploy/define_environment.html):

 - [x] I notice that you are using the GPU image for the hb120 vms (which do not have a GPU). Why?
 - [x]  I wanted to choose a `homefs_size_tb` of 1 but then received an error stating that the size must be in the range between 4 and 500. Why?
 - [x] The docs on [azure prerequisites](https://azure.github.io/az-hop/deploy/azure_prereqs.html) mention requirements on "the resource group", which made me think that I need to first create the resource group we provide to the `config.yml`. This thought was incorrect, and the deployment fails in that case. Please mention in the `config.tpl.yml` that the resource group will be created and should not exist.

 - [ ] The `key_vault_readers` field lacks documentation (which key vault? where to get this object id from?)

Suggestions for the [deploy step](https://azure.github.io/az-hop/deploy/deploy.html):
 * Please add a rough estimate of how long the `./build.sh -a apply` step is supposed to take (20 minutes? longer?)

**Comment by ltalirz** [comment]
@xpillons if you can comment on this point, we can close this issue as well

> * [ ]  The `key_vault_readers` field lacks documentation (which key vault? where to get this object id from?)

**Comment by xpillons** [comment]
`key_vault_readers` can grant read role on the azhop key vault to identities listed by this value.
