### ISSUE TITLE
document requirement for access to `graph.microsoft.com` scope

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#949]
## In what area(s)?

> /area administration

## Expected Behavior

After logging in to azure via the azure cli on WSL2 on my laptop, I can deploy azure hop.

## Actual Behavior

Deployment fails with

```
╷
│ Error: Error building account: Error getting authenticated object ID: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: ERROR: AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.
│ Trace ID: 5a8c4607-ed1a-4273-8020-176398865d00
│ Correlation ID: 5ea7a281-357a-4729-877b-1296fd127921
│ Timestamp: 2022-07-14 10:42:32Z
│ To re-authenticate, please run:
│ az login --scope https://graph.microsoft.com//.default
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 16, in provider "azurerm":
│   16: provider "azurerm" {
│
```

Interestingly, Linux is not among the allowed platforms of this list, which seems to make it impossible for me to deploy az-hop.

When I try to `az login --scope https://graph.microsoft.com//.default` manually, I end up with

<img width="213" alt="image" src="https://user-images.githubusercontent.com/1053245/178967706-705077c8-4dca-453b-8fa7-84bebb2999aa.png">

This despite the fact that my laptop actually *is* managed by Microsoft (but I guess this does not propagate down to the WSL2).
The same issue occurs when trying to deploy az-hop from an Ubuntu VM in azure.

I realize that this issue is specific to the access policies on my azure account.
For the az-hop docs, it would just make sense to document the requirement that users need to be able to log into the `graph.microsoft.com` scope via `az login --scope https://graph.microsoft.com//.default`

**Comment by ltalirz** [comment]
After digging a bit more, I read [here](https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration#graph-command-fails-with-aadsts50005-or-aadsts53000) that the Microsoft tenant has a conditional access policy in place that prevents users from accessing Microsoft Graph using the standard "device code flow".

Alternatives are the "authorization code flow" and using a service principal.
The "authorization code flow" [requires a working web browser on the machine where you're running it](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli#sign-in-interactively), which will typically not be the case on a deployer VM.

I tried the service principal route, but when doing so I get another error message when deploying az-hop:


```
$ ./build.sh -a apply
╷
│ Error: Error building AzureRM Client: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
│ 
│ To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
│ auth method - instructions for which can be found here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secre
t
│ 
│ Alternatively you can authenticate using the Azure CLI by using a User Account.
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 16, in provider "azurerm":
│   16: provider "azurerm" {
│ 
```

**Comment by xpillons** [comment]
WSL2 should allows you to login as a user and your device to be trusted, this is my setting. So there is something misconfigured I guess.
When using a deployer VM, the best scenario is to add a system managed identity to it and grant the roles documented in https://azure.github.io/az-hop/deploy/azure_prereqs.html 
Then you can logon to azure with `az login -i`

**Comment by ltalirz** [comment]
> WSL2 should allows you to login as a user and your device to be trusted, this is my setting. So there is something misconfigured I guess.

I see, so just to confirm: you can `az login --scope https://graph.microsoft.com//.default` on your WSL2?

The error message in my case says `User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.` which made me think that WSL2 is considered Linux and not supported.

**Comment by xpillons** [comment]
I just ran `az login` from my WSL2 session and it opens a browser from which I was able to authenticate. Nothing to do more. I'm on az cli 2.0.37

**Comment by ltalirz** [comment]
Thanks! Trying `az login --scope https://graph.microsoft.com//.default` again today now also uses the " authorization code flow", which does provide access to `graph.microsoft.com`. Perhaps I used the "device code flow" before, and then it no longer tried the "authorization code flow" when I tried to get access to the `graph.microsoft.com` scope.

To summarize my understanding: 
 * You can deploy az-hop from WSL2, when logging in using the "authorization code flow" (which is the default for `az login`)
 * You can deploy az-hop from a deployer VM, but only using a service principal or a system managed identity. This is because the "authorization code flow" is not available there (no web browser).
 * You cannot deploy az-hop from the Azure cli because you need to install terraform.
