### ISSUE TITLE
Prebuilt images

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#974]
Hi Xavier (cc @ltalirz),

Is it possible to have a few prebuilt images available to use during the install process please? Right now it seems that there's a shortage of N-series VMs on US East, which makes it difficult to continue the install process because we have to build our own images. Also, the image build is rather slow and, as far as I can gather, you get identical results for all builds. Is it a problem with requirements when publishing images, or the fact that they're changing too quickly?

Thanks!
Matt

**Comment by xpillons** [comment]
Yes this is something we are working on. There will be images in the marketplace for infrastructure VMs as well as for compute and viz nodes.
In the meantime, if you don't need viz node at all, you can change the imageid in the config file to be a standard market place image for CentOS 7.9 like OpenLogic:CentOS-HPC:7_9-gen2:latest and skip building the remote desktop image.

**Comment by matt-chan** [comment]
Thanks for the heads up! I'll do that.
