### ISSUE TITLE
Using ANF directly

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#977]
Hi @xpillons (cc @ltalirz), 

Could you let us know why you used lustre on top of ANF as opposed to directly mounting an ANF NFS share to the home directory? We are trying to decide whether the cost of the lustre VMs are justified or if we should strip them out.

Thanks!
Matt

**Comment by xpillons** [comment]
@matt-chan Lustre and ANF have two different purposes. Usually Lustre is used for scratch and fast temporary shared storage while ANF is used for keeping users home directories, application binaries, input and output data. 
Making Lustre an option is an open item we will work on and prioritize based on demand. If it's a high demand from your team let us knows.

**Comment by matt-chan** [comment]
Ah. Sorry I misunderstood the usage of ANF and Lustre. Thanks for clearing that up!

Do you have any resources on the sizing choices for the lustre config? The default configuration looks like it will be a fairly steep fixed cost for our customer ($3000/mo?).

**Comment by xpillons** [comment]
Closing as Lustre is now optional as per PR #1000

**Comment by ltalirz** [comment]
Thanks a lot, Xavier!
