### ISSUE TITLE
document how to modify pinned apps

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#980]
## In what area(s)?

> /area administration

## Describe the feature
Document how administrators can change which apps are pinned to the home dashboard.

The default setting contains an example of how to select an entire category.
One would just need to add a (commented out) example of the syntax for adding an individual app

https://github.com/Azure/az-hop/blob/c7663b68c44d519ae57d3ced4df4c92471a82864/playbooks/ood-overrides-common.yml#L96-L97

**Comment by xpillons** [comment]
This is a OnDemand feature documented here https://osc.github.io/ood-documentation/latest/customization.html#control-which-apps-appear-in-the-dashboard-navbar

**Comment by ltalirz** [comment]
thanks for the link @xpillons !

opened https://github.com/Azure/az-hop/pull/982 that adds the link as well as a commented example (tested)
