### ISSUE TITLE
documentation of upgrade path

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#987]
## In what area(s)?

> /area documentation

## Describe the feature

It would be useful to document the upgrade path for an existing az-hop instance.

For example, say, you've created an az-hop instance with az-hop repo v1.0.9 and you would like to upgrade to az-hop v1.0.24. 
What are the suggested steps to follow?

We realize that it may still a bit early to set up standards in this regard (e.g. based on semantic versioning), but it is nevertheless useful to administrators to have an idea of what to watch out for (even if it is just mentioned in the release notes, like: for this release, re-run terraform)

Mentioning @matt-chan for info

**Comment by xpillons** [comment]
Upgrading path will have to follow these steps :

- Read all versions notes to check if any breaking changes exists. If so update your config or take actions as described in the notes
- if infrastructure changes need to be applied run the build.sh
- remove ./playbooks/*.ok and run the install.sh 

this should probably be added to the documentation
