### ISSUE TITLE
Cyclecloud icons missing

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#988]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
> /area configuration

/area cyclecloud

> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Expected Behavior

Cyclecloud button icons should be present

## Actual Behavior

Icons are replaced with blank squares. Chrome developer console reports images failed to load.

![image](https://user-images.githubusercontent.com/1048117/180580046-4a609cb5-f0de-4189-b84b-a0e7212a9693.png)

## Steps to Reproduce the Problem

Present on a standard installation from master branch.

**Comment by xpillons** [comment]
Thnk you, this is solved by #985
