### ISSUE TITLE
check schema of config.yml before deploying

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#994]
## In what area(s)?

> /area administration

## Describe the feature

@matt-chan reports that he ran into issues multiple times because he had some typo in the config.yml.

Checking the `config.yml` against a schema before running it could prevent most issues of this type. Having a schema would also provide a reference of all the allowed fields, which is not always obvious (for example in the definition of the scheduler queues).

There are many Python packages (e.g. [genson](https://pypi.org/project/genson/)) that can be used to infer a JSON schema from an example JSON (or yaml) file and validate a given JSON (or yaml) file against that schema. And then there are tools like [json-schema-for-humans](https://github.com/coveooss/json-schema-for-humans) that can turn this into a nice-looking HTML documentation.

If there is interest in adding such a feature, I could run such a tool on the `config.yml` template and generate an example schema.

**Comment by xpillons** [comment]
Thank you for the suggestion. As we are working into a different deployment mechanism thru Bicep, the config file will change, so this work could be interesting to be done once this will be released.

**Comment by ltalirz** [comment]
addressed by https://github.com/Azure/az-hop/pull/1353
