### ISSUE TITLE
No error messages when quota or subscription prevents creation of nodes

### ISSUE THREAD

**Issue by matt-chan** [Azure/az-hop#995]
## In what area(s)?

/area job-scheduling

## Expected Behavior

When nodes are not available due to quota or subscription issues, it would be nice to have an indication of this in cyclecloud or ondemand. 

## Actual Behavior

Cyclecloud refuses to boot the required number of nodes but gives no error why. Ondemand indicates the job is queued and nothing changes. 

## Steps to Reproduce the Problem

Set quota to 120 vcpus. Schedule an mpi job on slurm requiring two hb120-16rsv2 nodes. Job refuses to run because required quota is 240vcpus (even though you only requested 32...)

**Comment by xpillons** [comment]
This is not a behavior we have control on, you have to understand your quota before configuring your cluster. As an admin you can check in the CycleUI how much quota you have by manually adding a node, which will display how many nodes can be added.
