### ISSUE TITLE
document how to compile codes

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#997]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
/area documentation
> /area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Describe the feature

One of the first things new users may need to do is to compile the codes they need.

Academic HPC systems often have a head node with a software environment that mirrors the one of the compute nodes and that can be used for compilation of codes.

If I understand correctly, in the az-hop setup, this is not the case and in order to compile codes it is always necessary to request an interactive job from the scheduler.

Just checking to confirm whether I understand this correctly; will add a bullet point to https://azure.github.io/az-hop/user_guide/index

**Comment by xpillons** [comment]
this is why you have CodeServer. It allows you to get a compute node software stack and compile apps.
